### PR TITLE
made the nav-bar items orientation proper

### PR DESCRIPTION
**Pull request by Sloth-Panda**
corresponds to issue - #57 

Before->
Screenshot (39)

After->
Screenshot (38)

### CODE REVIEW

**Comment by Sloth-Panda** [comment]
Hey, review the pr and let me know

**Comment by Sloth-Panda** [comment]
Kindly add dwoc and level-3 tags

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Annotation 2021-01-10 215956
I am still able to see the issue.

**Comment by Sloth-Panda** [comment]
That should not be like that did you just use ur live server @swapnilsparsh  cause I have fixed this only. 
And as the images of this rescue web app is not visible so ig u have not really run the project on the backend server.
and also I have fixed the dashboard only I mean after logging in where you land up that page so it should not be like that.
Anyways let me know after connecting with the backend and running the server not the live server one though

**Comment by swapnilsparsh** [comment]
> That should not be like that did you just use ur live server @swapnilsparsh cause I have fixed this only.
> And as the images of this rescue web app is not visible so ig u have not really run the project on the backend server.
> and also I have fixed the dashboard only I mean after logging in where you land up that page so it should not be like that.
> Anyways let me know after connecting with the backend and running the server not the live server one though

I didn't used the live server, I used the backend only to make the site live in order to see the issue that you have fixed but it doesn't seem to be fixed.

**Comment by Sloth-Panda** [comment]
oKay let me check again

**Comment by Sloth-Panda** [comment]
Screenshot (46)

It's look like this on my development server. I have made the pr ig did not push one or two things let me know soon if it works fine or not

**Comment by Sloth-Panda** [comment]
Hey, I just did the landing page, not the emergency page so it is showing like that to you

**Review by swapnilsparsh — COMMENTED** [review]
Resolve the conflicts

**Comment by Sloth-Panda** [comment]
@swapnilsparsh has resolved them is it okay now?

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh has resolved them is it okay now?

I am checking , wait

**Comment by swapnilsparsh** [comment]
@Sloth-Panda 
It's working fine on all the pages except the home page.
There is a slight orientation problem which you have to fix it and there is a bug when I am checking it if it is repsonsive or not then the dropdown automatically opens up.
Annotation 2021-01-17 183916
Annotation 2021-01-17 183947

**Comment by Sloth-Panda** [comment]
Leave the toggle part for now i have already made the issue few days back for the same only will do that  and for the other part you mentioned i am checking

**Comment by swapnilsparsh** [comment]
> Leave the toggle part for now i have already made the issue few days back for the same only will do that and for the other part you mentioned i am checking

I can't simply merge your code having bugs in it so if you are comfortable then close the other issue and work only on this issue and when it gets resolved then start doing work on other issue as you have opened many issue simultaneously so there might be a confusion.

**Comment by Sloth-Panda** [comment]
Okay but i have fixed the page before logging in just the part that i mentioned so asked

**Comment by swapnilsparsh** [comment]
> Okay but i have fixed the page before logging in just the part that i mentioned so asked

That part is not fixed as you can see in the above comment where I attached the photo.

**Comment by Sloth-Panda** [comment]
Oh okay I will look into it

**Pull request closed without merging**
