### PR TITLE
Change password functionality added

### PR DESCRIPTION
**Pull request by somya51p**
## Related Issue or bug
  This pull request is associated to **issue number #197.**

Fixes: #[issue number that will be closed through this PR]

#### Describe the changes you've made
Added a page for changing the currently signed-in user's password. If a user wants to change a password due to security reasons, he/she can change it.

## Type of change
**New Feature** added.

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.

## Screenshots

 
 

 
 
 
 
 
 @swapnilsparsh @sakshikhachane Please review this issue.

### CODE REVIEW

**Review by sakshikhachane — CHANGES_REQUESTED** [review]
@somya51p Good work! Just some changes.
- [ ] Just some changes. Increase top margin of `changepassword` page.
- [ ] Make page responsive.
- [ ] Change the font style of `CHANGE PASSWORD` title.

**Comment by somya51p** [comment]
@sakshikhachane I have made the suggested changes. Please go through them once and review the same.

**Comment by somya51p** [comment]
@sakshikhachane @swapnilsparsh Please review the PR. I have made the suggested changes.

**Comment by swapnilsparsh** [comment]
> @sakshikhachane I have made the suggested changes. Please go through them once and review the same.
> 
> 

Use some illustration instead of photo that you have used.

**Comment by somya51p** [comment]
@sakshikhachane @swapnilsparsh I have made the suggested changes. Please review the PR. Thank you!

**Comment by somya51p** [comment]
@swapnilsparsh Please review the PR. Thank You!

**Comment by swapnilsparsh** [comment]
> @sakshikhachane @swapnilsparsh I have made the suggested changes. Please review the PR. Thank you!
> 
> 

Search for some other illustrations
You can search on google images "change password vector art", from there you can choose some desgin as there are many good options.

**Comment by somya51p** [comment]
@swapnilsparsh Please review the PR.

**Comment by swapnilsparsh** [comment]
@somya51p  Resolve the conflicts

**Pull request closed without merging**
