### PR TITLE
Modification performed in women_safety_laws.md file

### PR DESCRIPTION
**Pull request by Kavs-123**
### Improve the women's laws HTML documentation
  - The assignee is asked to perform improvements in the `Women_safety_laws documentation`

#### Describe the changes you've made
I have performed many changes that were needed in the provided documentation to improve it to the fullest.
The changes performed are as follows : 
   - Implemented proper formatting of the document.
   - Presented the statements in bullet points format wherever needed to enhance the clarity and understanding.
   - Highlighted the required words or numbers to increase readability and highlight important words that needs to be emphasized.
   - Provided headings with the required heading style to reach perfectivity. 
   - Added as well as deleted the whitespace wherever desired.
   - Enhanced and revised the document once grammatically.

## Type of change

Please delete options that are not relevant.

- [✓] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [✓] Code style update (formatting, local variables)
- [✓] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [✓] This change requires a documentation update

## How Has This Been Tested?
I have previewed my formatted markdown file properly before finalising the same through online markdown preview editor.
I tried to give importance to smallest possible area that can cause error in formatting through proper preview mode. 
#### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
`NA`

## Checklist:

- [✓] My code follows the style guidelines of this project.
- [✓] I have performed a self-review of my own code.
- [✓] I have commented my code, particularly in hard-to-understand areas.
- [✓] I have made corresponding changes to the documentation.
- [✓] My changes generate no new warnings.
- [✓] I have added tests that prove my fix is effective or that my feature works.
- [✓] New and existing unit tests pass locally with my changes.
- [✓] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |
 Original 
**unformatted-pic** 
Updated
<b>formatted-pic</b>

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Improve the government initiatives section also.

**Comment by Kavs-123** [comment]
> Improve the government initiatives section also.

Ok sure @swapnilsparsh

**Comment by swapnilsparsh** [comment]
> Hey @swapnilsparsh,
> I have performed the further improvements required in the 'women_safety_laws.md' file.
> I have improved the `government initiatives section`.
> The improvements performed are :
> 
> * Sentences have been improvised by specifying them in bullet points.
> * Grammatically once more the sentences have been modified.
> * Required spaces have been added as well as removed.
> * Enhanced clarity has been emphasized.
> * Important numbers as well as words have been highlighted.

That's great but I am unable to see the changes that you have made.

**Comment by Kavs-123** [comment]
> > Hey @swapnilsparsh,
> > I have performed the further improvements required in the 'women_safety_laws.md' file.
> > I have improved the `government initiatives section`.
> > The improvements performed are :
> > 
> > * Sentences have been improvised by specifying them in bullet points.
> > * Grammatically once more the sentences have been modified.
> > * Required spaces have been added as well as removed.
> > * Enhanced clarity has been emphasized.
> > * Important numbers as well as words have been highlighted.
> 
> That's great but I am unable to see the changes that you have made.

Hey, @swapnilsparsh 
 I just it now pushed again!
I hope it is visible now!
Please review it !!

**Pull request merged**
