### PR TITLE
FAQ Page Added

### PR DESCRIPTION
**Pull request by VaibhavSharma24**
Fixes: #[issue number #215 that will be closed through this PR]

#### Describe the changes you've made
Added a faq page 

screenshot : 
[Doc1.docx](https://github.com/swapnilsparsh/Rescue/files/6321129/Doc1.docx)

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Smallont
Fix this
<hr>
Follow the website design (Fonts, colour)

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
1. Still, it is not fixed.
2. Use the FAQ heading in the center and use some vector art or illustration with the heading.
3. Dropdown menu bg color should be white with a black heading.

**Comment by sakshikhachane** [comment]
@VaibhavSharma24 Any updates?

**Review by sakshikhachane — CHANGES_REQUESTED** [review]
- [ ] Change the pink color to the white color, refer to `Women Safety Laws` page.
- [ ] On hovering the question, the text color is becoming blue and is underlined. Remove this and keep it the same as the `Women Safety Laws` page.
- [ ] Whenever any FAQ is clicked it scrolls up and only the answer is visible. The question should be displayed along with the answer.
- [ ] Check for responsivness of the page.

**Review by sakshikhachane — APPROVED** [review]

**Pull request merged**
