### PR TITLE
create contact page enhanced

### PR DESCRIPTION
**Pull request by mansijain980**
Fixes: #157
 
Enhanced create page.

### CODE REVIEW

**Comment by mansijain980** [comment]
> Fixes: #157
> 
> Enhanced create page.

check it.

**Comment by swapnilsparsh** [comment]
@mansijain980 There is no captcha box, fix it please.

**Comment by mansijain980** [comment]
@swapnilsparsh 
It is showing this 
image
I have to add this domain in the list of supported domains.

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh
> It is showing this
> image
> I have to add this domain in the list of supported domains as localhost is not supported by them.

In the master branch, there is no such error.

**Comment by swapnilsparsh** [comment]
@mansijain980 Resolve the conflicts.

**Comment by mansijain980** [comment]
@swapnilsparsh This PR will count under GSSOC"21 ?

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh This PR will count under GSSOC"21 ?

Yes

**Pull request merged**
