### PR TITLE
Improved UI of Register and Sign in templates using Grid

### PR DESCRIPTION
**Pull request by Tarun-Kamboj**
## Related Issue or bug
  - Improved UI of `Register` and `Sign in` templates using Grid system.

Fixes: #164

#### Describe the changes you've made
I used the bootstrap grid system to improve the UI of the `Register` and `Sign in` templates. I also adjusted the code so that it looks good on narrow screens too.

## Type of change

Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
`NA`

## Checklist:
- [x] My code follows the code style of this project.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
Screenshot (200)  | Screenshot (212) |

### CODE REVIEW

**Review by sakshikhachane — CHANGES_REQUESTED** [review]
- [ ] Please increase the top margin of the form details div where `username` etc fields are there.
- [ ] Reduce the size of `New to Rescue? Create an Account`.
- [ ] Add the hovering effects to the button as it was before making changes.

**Comment by Tarun-Kamboj** [comment]
> * [ ]  Reduce the size of `New to Rescue? Create an Account`.

On the narrow screen or wide?

**Comment by sakshikhachane** [comment]
> > * [ ]   Reduce the size of `New to Rescue? Create an Account`.
> 
> On the narrow screen or wide?

On the wide screen.

**Comment by Tarun-Kamboj** [comment]
@sakshikhachane i made the requested changes. Have a look. I made the login button similar to the register button as it was much better.

**Review by sakshikhachane — APPROVED** [review]

**Pull request merged**
