### PR TITLE
Enhanced Create contact page issue - 157

### PR DESCRIPTION
**Pull request by zaverisanya**
## Related Issue or bug
Enhanced create contact page with css and bootstrap

Fixes: #157

#### Describe the changes you've made
1) Added Jumbotron
2) Edited width of form 
3) Edited width of select box
4) Edited labels

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 
Run python manage.py runserver

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |
 
 
Screenshot (699)

### CODE REVIEW

**Review by sakshikhachane — CHANGES_REQUESTED** [review]
The changes are looking good. But, the footer is distorted on big and small screens. Please fix this.

image

**Comment by zaverisanya** [comment]
I have made the recommended change, please check now!

**Review by sakshikhachane — CHANGES_REQUESTED** [review]
Looking good. Just fix the `create_contract` page on smaller screens.
- [ ] Increase the width of the form on smaller screens.
- [ ] Reduce the space below the form. Make the space equal from top and bottom.

image

**Comment by sakshikhachane** [comment]
@zaverisanya Any updates?

**Comment by zaverisanya** [comment]
@sakshikhachane  I will complete it by tonight!

**Comment by zaverisanya** [comment]
I have made the recommended changes. Please check!

**Review by sakshikhachane — APPROVED** [review]

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
create contact

 Fix the page on smaller screens.

**Comment by zaverisanya** [comment]
I have made the recommended changes. Please check! @swapnilsparsh

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Few changes:
1. Fix the page on smaller screens.
2. Add some illustrations.
3. Remove the grey box.

**Comment by zaverisanya** [comment]
Sir, please elaborate the 2nd point, what exactly do you mean by 'adding illustrations'?

**Comment by swapnilsparsh** [comment]
> Sir, please elaborate the 2nd point, what exactly do you mean by 'adding illustrations'? @swapnilsparsh

Have a look at register page there you can see a illustration on your right side or you can google it.

**Comment by swapnilsparsh** [comment]
@zaverisanya  Any updates ?

**Comment by sakshikhachane** [comment]
@zaverisanya  Any updates?

**Pull request closed without merging**
