### PR TITLE
styled helpline, added meta tag to common

### PR DESCRIPTION
**Pull request by tanishq-arya**
## Related Issue or bug
  - Added style and made changed to make the page responsive

Fixes: #200 

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |
 
 
Screenshot (998)
Screenshot (996)
Screenshot (997)

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
1. Keep only Call writtern there, remove Now from "Call Now".
2. For small screen number should come in one line rathere than breaking it in two parts.

**Comment by tanishq-arya** [comment]
Okay. I'll make the changes

**Comment by tanishq-arya** [comment]
Screenshot (1004)
Screenshot (1003)

**Comment by tanishq-arya** [comment]
This is for the helpline page. Do you want me to make a new issue for the login page ?

**Comment by swapnilsparsh** [comment]
> This is for the helpline page. Do you want me to make a new issue for the login page ?

Issues which I have asked you to resolve has happened by you while you were resolving the helpline page issue, so in order to merge your PR you have to resolve the issues which are there.

**Comment by tanishq-arya** [comment]
Okay. I will make the changes.

**Comment by tanishq-arya** [comment]
image
I am getting this error. Can you help me with this ?

**Comment by swapnilsparsh** [comment]
> image
> I am getting this error. Can you help me with this ?

There are some changes that have been done to slideshow backend, kindly rebase your code to master then it should resolve this issue.

**Comment by swapnilsparsh** [comment]
> image
> I am getting this error. Can you help me with this ?

I have opened the issue for this error #236

**Comment by swapnilsparsh** [comment]
> image
> I am getting this error. Can you help me with this ?

Resolved this issue, kindly rebase your code with master branch.

**Comment by tanishq-arya** [comment]
> > image
> > I am getting this error. Can you help me with this ?
> 
> Resolved this issue, kindly rebase your code with master branch.

Okay working on the changes requested

**Comment by tanishq-arya** [comment]
Screenshot (1162)
Screenshot (1160)
Screenshot (1161)

**Comment by tanishq-arya** [comment]
I think this is a level 3 issue now @swapnilsparsh I hope you would also agree with me.

Also I looked into the code it was not mine. I only made changes to the register page. Login page was done by someone else and it was committed 7 days ago when I wasn't aware of the changes and 6 days I asked you if I should make a new issue for the login page. Please take a look at this. 

https://github.com/swapnilsparsh/Rescue/commit/2276bf4caad3e3afe11eea90a653d0417a193e4e

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Few changes:
1. Use same font as used in register page
2. Use the same font size as used in register page
3. Align the items in center as it is there in register page

**Comment by tanishq-arya** [comment]
> Few changes:
> 
> 1. Use same font as used in register page
> 2. Use the same font size as used in register page
> 3. Align the items in center as it is there in register page

On it.

**Comment by tanishq-arya** [comment]
Screenshot (1198)
Screenshot (1193)
Screenshot (1194)
Screenshot (1195)

**Comment by tanishq-arya** [comment]
Also I raised another issue which was caused in the register page. #248 Please assign it to me.

**Comment by sakshikhachane** [comment]
> Also I raised another issue which was caused in the register page. Issue number 248 Please assign it to me.

@swapnilsparsh I also feel the same. What are your views?

**Comment by swapnilsparsh** [comment]
> > Also I raised another issue which was caused in the register page. Issue number 248 Please assign it to me.
> 
> @swapnilsparsh I also feel the same. What are your views?

#248 has been closed as there was no bug as mentioned in the issue.

**Comment by tanishq-arya** [comment]
I checked using chrome if its resolved then its okay I guess.

**Comment by tanishq-arya** [comment]
> Few changes:
> 
> 1. Use same font as used in register page
> 2. Use the same font size as used in register page
> 3. Align the items in center as it is there in register page

Done

**Comment by swapnilsparsh** [comment]
**Fix the register page**
FIx

**Comment by tanishq-arya** [comment]
@swapnilsparsh That's why I made a new issue #248  . Can you open that and assign it to me.

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh That's why I made a new issue #248 . Can you open that and assign it to me.

Currently the old login page is used so the changes which you have made in the login page have created some new bugs in register page which has to be resolved by you only.

**Comment by tanishq-arya** [comment]
> > @swapnilsparsh That's why I made a new issue #248 . Can you open that and assign it to me.
> 
> Currently the old login page is used so the changes which you have made in the login page have created some new bugs in register page which has to be resolved by you only.

Did you look into this ? This is my code which was modified and this is being used. If you still want me to do the changes in this PR I am working on it But my code was perfectly fine and you can view the screenshots in the PR that was merged.
https://github.com/swapnilsparsh/Rescue/commit/2276bf4caad3e3afe11eea90a653d0417a193e4e

**Comment by tanishq-arya** [comment]
Screenshot (1233)
Screenshot (1230)
Screenshot (1231)
Screenshot (1232)

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
**FIx this** 
Annotation 2021-04-17 005425

<hr>

Register page is working fine but its looking very zoomed, if you want you can keep the way it is right now else reduce the zoom.

**Comment by tanishq-arya** [comment]
> **FIx this**
> Annotation 2021-04-17 005425
> 
> Register page is working fine but its looking very zoomed, if you want you can keep the way it is right now else reduce the zoom.

Will look into this.

**Comment by tanishq-arya** [comment]
image

**Comment by swapnilsparsh** [comment]
> > **FIx this**
> > Register page is working fine but its looking very zoomed, if you want you can keep the way it is right now else reduce the zoom.
> 
> @swapnilsparsh I would love to work on this, but this is a completely different page. Can you please consider raising a new issue for this ? It is probably because all 3 modals are in the same row in mobile-view and everything is overflowing out of the body.

I can't open a new issue for this as this bug has been created by you only while you were working on this issue so you have to fix it by yourself only.

**Comment by tanishq-arya** [comment]
Did you take a look at the html page itself ? There is not a single line of CSS that I changed that's why I asked you to look into that commit.

**Comment by tanishq-arya** [comment]
Screenshot (1317)
Screenshot (1314)
Screenshot (1315)
Screenshot (1316)

**Comment by tanishq-arya** [comment]
@sakshikhachane There are some conflicts with this branch as another PR was merged before this. I am resolving them by accepting them all. If anything else changes I will resolve them but in a new issue. I hope you understand.

**Comment by sakshikhachane** [comment]
> @sakshikhachane There are some conflicts with this branch as another PR was merged before this. I am resolving them by accepting them all. If anything else changes I will resolve them but in a new issue. I hope you understand.

@swapnilsparsh Is it okay?

**Pull request merged**
