### PR TITLE
Added user profile edit option 

### PR DESCRIPTION
**Pull request by SnehaVeerakumar**
#### Describe the changes you've made
 User can change their password and update their profile from "user" drop down in navigation bar.

Fixes: #194 

##Working video
https://drive.google.com/file/d/1jWD6C4rjfXPN8mGnFF7JhL8w25DIc-g4/view?usp=sharing

##Project set up
`python manage.py makemigrations`
`python manage.py migrate`

Making migrations is necessary to migrate created models.

## Type of change
User can now edit their details

Example how to mark a checkbox :-
- [x] My code follows the code style of this project.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

By deploying in localhost

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:
- [x]  My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

##Screenshots
Screenshot (1034)
Screenshot (1035)
Screenshot (1036)
Screenshot (1037)

### CODE REVIEW

**Comment by swapnilsparsh** [comment]
@SnehaVeerakumar If the email id is already registered and then user is changing its email then did it show that email is available or not ?

**Comment by SnehaVeerakumar** [comment]
> @SnehaVeerakumar If the email id is already registered and then user is changing its email then did it show that email is available or not ?

username and email cannot be changed as it is unique and verified at the time of registration

**Comment by SnehaVeerakumar** [comment]
If the email and username should be changed, I need to connect this with "users" field but you cannot have other fields such as contact number, age, gender.

**Comment by khanfarhan10** [comment]
I think it's best to leave out the useremail unchanged.

**Comment by SnehaVeerakumar** [comment]
> I think it's best to leave out the useremail unchanged.

Yes, in this code username cannot be changed

**Comment by SnehaVeerakumar** [comment]
Working demo :
https://1drv.ms/v/s!AhQCqna6zNwBjimSQPH1mWovWGcS?e=vGV8eB

**Comment by SnehaVeerakumar** [comment]
> Working demo :
> https://1drv.ms/v/s!AhQCqna6zNwBjimSQPH1mWovWGcS?e=vGV8eB


@swapnilsparsh @khanfarhan10

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Disable the email changing field as the user is not allowed to change the email once it is registered.

**Comment by SnehaVeerakumar** [comment]
> Disable the email changing field as the user is not allowed to change the email once it is registered.

Done.

**Comment by SnehaVeerakumar** [comment]
@swapnilsparsh @khanfarhan10 Any updates?

**Review by sakshikhachane — CHANGES_REQUESTED** [review]
- [ ] Update password is displayed on the navbar only for `home`, not for other pages. The navbar should be the same for every page.
- [ ] How do I view the `profile` page directly without entering the URL? Is it through the `update password` link. 
- [ ] Add better hovering effects for the `username` and `update password`
- [ ] In `profile` page, align `SAVE CHANGES` button to the center.
- [ ] On right side column of `age` add `contact number` field and likewise adjust `city` and `gender` side by side.

**Comment by SnehaVeerakumar** [comment]
> * [ ]  Update password is displayed on the navbar only for `home`, not for other pages. The navbar should be the same for every page.
> * [ ]  Add the dropdown to the `username` and in that dropdown add `Profile` and `logout` option.
> * [ ]  Add better hovering effects for the `username` and `update password`
> * [ ]  In `profile` page, align `SAVE CHANGES` button to the center.
> * [ ]  On right side column of `age` add `contact number` field and likewise adjust `city` and `gender` side by side.

Thank you for the review. I will update it by tomorrow

**Comment by SnehaVeerakumar** [comment]
@sakshikhachane  I have added only profile update which is through user name click. Now that will be added to the dropdown. Please correct me if I am wrong.

**Comment by sakshikhachane** [comment]
> @sakshikhachane I have added only profile update which is through user name click. Now that will be added to the dropdown. Please correct me if I am wrong.

Yes, you are right.

**Comment by SnehaVeerakumar** [comment]
> > @sakshikhachane I have added only profile update which is through user name click. Now that will be added to the dropdown. Please correct me if I am wrong.
> 
> Yes, you are right.
> Have you included `update password`?

Yes, I got your point which says the fields added by this PR will be in the dropdown of username including logout option.

**Comment by SnehaVeerakumar** [comment]
Changes made :
1.  All the links are now accessible from anywhere navigation bar is available.
2.  In profile page and contact page, SAVE CHANGES button is alligned to center.
3.  Allignment in profile edit section have been made.
4.  Dropdown has 3 fields : Update profile, Update password, logout

Screenshots : 
Screenshot (1108)
Screenshot (1110)


Video demonstrating the links are accessible from other pages : 
https://1drv.ms/v/s!AhQCqna6zNwBjis8U4RTIjktiWA9?e=wRI7Ax

**Comment by SnehaVeerakumar** [comment]
All the mentioned changes have been made. Also, in changes password page, I have aligned SAVE CHANGES to center.

Screenshots and video :
https://1drv.ms/u/s!AhQCqna6zNwBjjLPAKq_0FskGfw0?e=Xcb8F0

@sakshikhachane @swapnilsparsh @khanfarhan10

**Comment by SnehaVeerakumar** [comment]
Any updates ? 
@sakshikhachane @swapnilsparsh @khanfarhan10

**Review by sakshikhachane — CHANGES_REQUESTED** [review]
- [ ] Remove the update password page as it is created in #197.
- [ ] Add heading/title to the `profile` page.
- [ ] For smaller devices, the form should be in the center and increase the font size as well.
- [ ] Reduce the width of `Save Changes` button
- [ ] On clicking the `Save changes` button, I am getting this error. 
image

Note -I have logged in through the google account.

**Comment by SnehaVeerakumar** [comment]
> * [ ]  Remove the update password page as it is created in #197.
> * [ ]  Add heading/title to the `profile` page.
> * [ ]  For smaller devices, the form should be in the center and increase the font size as well.
> * [ ]  Reduce the width of `Save Changes` button
> * [ ]  On clicking the `Save changes` button, I am getting this error.
>   image
> 
> Note -I have logged in through the google account.

Email field must be removed by the suggestion of project admin.. i thought i did. I will check it once.

**Comment by sakshikhachane** [comment]
@SnehaVeerakumar Any updates?

**Comment by SnehaVeerakumar** [comment]
> @SnehaVeerakumar Any updates?

I will update by tomorrow. Sorry for the delay

**Comment by SnehaVeerakumar** [comment]
I am so sorry. I am almost done and my PR will be all set to review tomorrow early morning. Due to hackathon I couldn't keep up the word. Sorry :(

**Comment by SnehaVeerakumar** [comment]
@sakshikhachane  I am facing an issue. The same file works fine in local machine but when I try to clone and run, I am getting "data referenced before assignment" error after "save changes"

Video of perfectly working project : https://1drv.ms/v/s!AhQCqna6zNwBjjQjY-dQWXQ7zqa4?e=4X9oAT 

Kindly suggest me a way.. both the codes are same and I have no idea why I get that error..

There are 3 possibilities now. You can run this repo and see if you get the same error or you can add someone with me in this issue to help me or unassigning me. The last option is in worst case please, I have put so much effort in this issue. It is your call now !

Thank you for being patient !

**Comment by sakshikhachane** [comment]
@SnehaVeerakumar I will have a talk with Project Admin and will let you know.

**Comment by SnehaVeerakumar** [comment]
> @SnehaVeerakumar I will have a talk with Project Admin and will let you know.

Once you try running the program ! What if it works as it is working in my local machine

**Comment by swapnilsparsh** [comment]
@SnehaVeerakumar Can you tell me what problem are you facing?

**Comment by SnehaVeerakumar** [comment]
> @SnehaVeerakumar Can you tell me what problem are you facing?

Are you facing any issue with the code in PR ?

My problem : My code works fine locally but if i clone the code in my PR, I get "data referenced before the assignment" error.

If it works fine for you, then no issues.

**Comment by swapnilsparsh** [comment]
> > @SnehaVeerakumar Can you tell me what problem are you facing?
> 
> Are you facing any issue with the code in PR ?
> 
> My problem : My code works fine locally but if i clone the code in my PR, I get "data referenced before the assignment" error.
> 
> If it works fine for you, then no issues.

I am also facing the issue as I am not able to review your PR.

**Comment by SnehaVeerakumar** [comment]
> > > @SnehaVeerakumar Can you tell me what problem are you facing?
> > 
> > 
> > Are you facing any issue with the code in PR ?
> > My problem : My code works fine locally but if i clone the code in my PR, I get "data referenced before the assignment" error.
> > If it works fine for you, then no issues.
> 
> I am also facing the issue as I am not able to review your PR.

Sorry, I did not get you. Why are you not able to review the PR?
Is there anything to resolve from my side other than merge conflicts ?

**Comment by swapnilsparsh** [comment]
> > > > @SnehaVeerakumar Can you tell me what problem are you facing?
> > > 
> > > 
> > > Are you facing any issue with the code in PR ?
> > > My problem : My code works fine locally but if i clone the code in my PR, I get "data referenced before the assignment" error.
> > > If it works fine for you, then no issues.
> > 
> > 
> > I am also facing the issue as I am not able to review your PR.
> 
> Sorry, I did not get you. Why are you not able to review the PR?
> Is there anything to resolve from my side other than merge conflicts ?

I will try to fix the issue which I am facing while reviewing your PR, give me some time.
Thank you for being patient.

**Pull request closed without merging**
