### PR TITLE
Added Mobile SMS Alert Feature

### PR DESCRIPTION
**Pull request by harshakhmk**
## Related Issue or bug
  - Add a feature that alert message should go on saved phone number 
Fixes: #[6]

#### Describe the changes you've made
Added an SMS alert feature that goes to all saved contacts during an emergency parallelly with email and WhatsApp notifications that are sent.
For the SMS provider, I have used the Twilio API service which is free up to a certain duration but seems best among its alternatives, as the alert should be sent as soon as possible others took a long time to do this task whereas Twilio doesn't take much time
I have also updated the requirements.txt as there is an additional package required for loading environment variables which is 
python-dotenv==0.17.1

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a little documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

 ## Working Video:
 

https://user-images.githubusercontent.com/56113657/117696633-274b4600-b1df-11eb-9365-bad26939c23e.mp4

### CODE REVIEW

**Comment by swapnilsparsh** [comment]
@harshakhmk Can you add a working video?

**Comment by swapnilsparsh** [comment]
I will be waiting for the working video till then I will inspect your code.

**Comment by swapnilsparsh** [comment]
@harshakhmk Twilio has a limitation I guess, is there any alternative method as I have used Twilio when I was working on this issue.

**Comment by harshakhmk** [comment]
> @harshakhmk Twilio has a limitation I guess, is there any alternative method as I have used Twilio when I was working on this issue.

@swapnilsparsh 
I found Twilio as the best among its alternatives as delivers messages quickly which is mandatory when someone is in emergency. Other solutions were using smtplib which can deliverer SMS but it takes more than 15min to deliver SMS which is not good in an emergency and sometimes it doesn't even deliver a message.
Even though Twilio is economical, it would definitely suit the purpose.
If you have any other alternatives, you can share them with me, I will try implementing them.

**Comment by swapnilsparsh** [comment]
> > @harshakhmk Twilio has a limitation I guess, is there any alternative method as I have used Twilio when I was working on this issue.
> 
> @swapnilsparsh
> I found Twilio as the best among its alternatives as delivers messages quickly which is mandatory when someone is in emergency. Other solutions were using smtplib which can deliverer SMS but it takes more than 15min to deliver SMS which is not good in an emergency and sometimes it doesn't even deliver a message.
> Even though Twilio is economical, it would definitely suit the purpose.
> If you have any other alternatives, you can share them with me, I will try implementing them.

Sorry for the inconvenience caused but we are looking for an alternative to Twilio only as we have used Twillio in past and it's not good enough, if possible then use some alternative of Twillio other than smtplib as it takes time.

**Comment by khanfarhan10** [comment]
Same problem here : Merge Conflicts Exist: @harshakhmk

**Comment by harshakhmk** [comment]
> Same problem here : Merge Conflicts Exist: @harshakhmk

That's because I have changed some part of the code in views and also this branch is not up to date

**Comment by harshakhmk** [comment]
I have found an alternative for SMS alert, is this still needs to be addressed

**Comment by swapnilsparsh** [comment]
> I have found an alternative for SMS alert, is this still needs to be addressed
> @swapnilsparsh

If you want to contribute to the project you can but you will not be getting any points for this PR in GSSOC 21.

**Comment by swapnilsparsh** [comment]
> Lol I don't need any points, tell me whether my name gets added to the contributor's list?

Yes, your name will be added to the contribution list.

**Comment by harshakhmk** [comment]
Can u reopen this PR

**Pull request closed without merging**
