### PR TITLE
Very new commits after deleting the footer changes!

### PR DESCRIPTION
**Pull request by SUMEKAGARWAL**
@swapnilsparsh @sakshikhachane !
Removed the listed modifications of footer and kept everything else intact.
Have a look at this and if no changes required, merge my new PR.

### CODE REVIEW

**Comment by SUMEKAGARWAL** [comment]
Please have a look on this!
@swapnilsparsh @sakshikhachane

**Comment by swapnilsparsh** [comment]
> Please have a look on this!
> @swapnilsparsh @sakshikhachane

Resolve the conflicts.

**Comment by SUMEKAGARWAL** [comment]
> > Please have a look on this!
> > @swapnilsparsh @sakshikhachane
> 
> Resolve the conflicts.

Done!

**Comment by SUMEKAGARWAL** [comment]
@swapnilsparsh All the conflicts are resolved.

**Comment by SUMEKAGARWAL** [comment]
Hello @swapnilsparsh ,
Please try to review my PR.

**Comment by swapnilsparsh** [comment]
> Hello @swapnilsparsh ,
> Please try to review my PR.
> I am waiting since 8 days. So, please have a look after it.

Please reosolve the conflicts.

**Comment by SUMEKAGARWAL** [comment]
@swapnilsparsh Done!

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh Done!

Can you tag the issue which was assigned to you as it wil be more easier to look after your PR ?

**Comment by SUMEKAGARWAL** [comment]
- In Women's Rights section, when we hover on the block, there is no action. Its responsive when we hover on the text instead. So, I will add that functionality. The same is active in the other section-"Women's Safety Laws".
- While creating a new contact, its mandatory to enter the email-id. What if parents don't have mail. So it shouldn't be mandatory.
- Deleting of contact should include the titles as "YES" or "NO" according to the question...Q.)Are you sure you want to permanently remove named contact?

**Comment by SUMEKAGARWAL** [comment]
@swapnilsparsh Done.

**Comment by SUMEKAGARWAL** [comment]
Hello @sakshikhachane ,
Is this issue closed or is it under review?

**Comment by sakshikhachane** [comment]
The issue isn't closed but you have made 2 PRs for the same issue. That's why I have closed your first PR as you were showing the changes in the second PR.

**Comment by SUMEKAGARWAL** [comment]
@sakshikhachane Ohkk...sorry for taking it wrong.
By the way, when will my PR will be merged?

**Comment by swapnilsparsh** [comment]
> @sakshikhachane Ohkk...sorry for taking it wrong.
> By the way, when will my PR will be merged?

Resolve the conflicts

**Comment by SUMEKAGARWAL** [comment]
> > @sakshikhachane Ohkk...sorry for taking it wrong.
> > By the way, when will my PR will be merged?
> 
> Resolve the conflicts

done!

**Comment by swapnilsparsh** [comment]
@SUMEKAGARWAL As you have mentioned in issue that "While creating a new contact, its mandatory to enter the email-id. What if parents don't have mail. So it shouldn't be mandatory."

Email should be mandatory as the location will be sent via both mail and phone.
Fix it.

**Comment by SUMEKAGARWAL** [comment]
@swapnilsparsh 
But what if the parents, only moms in specific , who probably dont have the mailID?
If in case I make it mandatory, these people who dont have mails, cannot use our website at all.

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh
> But what if the parents, only moms in specific , who probably dont have the mailID?
> If in case I make it mandatory, these people who dont have mails, cannot use our website at all.

Nowdays everybody has mail and if mail will not be necessary then the emergency mail can not be sent.

**Comment by SUMEKAGARWAL** [comment]
@swapnilsparsh ok then, I just need to remove the mandatory part right?

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh ok then, I just need to put the mandatory part right?

Yes

**Comment by swapnilsparsh** [comment]
@SUMEKAGARWAL If possible close this PR and open a new PR linking your issue and resolve the conflicts also

**Pull request closed without merging**
