### PR TITLE
Added link to call icons to call the mentioned helpline numbers in helpline_numbers.html

### PR DESCRIPTION
**Pull request by kanishka8276**
## Related Issuse or bug
  - #125 

Fixes: #125 

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

I have linked the phone icons to the corresponding helpline numbers  such that when they are clicked a call is made to the associated number.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 
Ran it in my localhost and tried using the link.
#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.
NA
## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 
Screenshot (61)

### CODE REVIEW

**Comment by kanishka8276** [comment]
@sakshikhachane  done!

**Comment by sakshikhachane** [comment]
@kanishka8276 Thanks for your cooperation.

**Comment by swapnilsparsh** [comment]
@sakshikhachane 
It's just a suggestion that there should be icon infront of the number so that if user wants to dial landline number or phone number then he/she can do that rather than keeping a default number.

**Comment by kanishka8276** [comment]
Ok! So then shall I remove the call icon which is in the left because so many call icons in a row won't look good.

**Comment by swapnilsparsh** [comment]
> Ok! Should I make these suggested changes @swapnilsparsh ? And if yes,then shall I remove the call icon which is in the left because so many call icons in a row won't look good.

Let @sakshikhachane decide.

**Comment by sakshikhachane** [comment]
> @sakshikhachane
> It's just a suggestion that there should be icon infront of the number so that if user wants to dial landline number or phone number then he/she can do that rather than keeping a default number.

It is indeed a good suggestion. @kanishka8276 Please do the changes.

**Comment by sakshikhachane** [comment]
> Ok! Should I make these suggested changes @swapnilsparsh ? And if yes,then shall I remove the call icon which is in the left because so many call icons in a row won't look good.

Add bullets instead of call icons.

**Comment by kanishka8276** [comment]
Ok!  I will do that.

**Comment by kanishka8276** [comment]
Screenshot (70)

**Comment by sakshikhachane** [comment]
@kanishka8276 Always keep your forked repo updated with the original repo. Please do the same.

**Comment by kanishka8276** [comment]
Ok!
Actually when I made the request it was up to date.

**Comment by kanishka8276** [comment]
@sakshikhachane I have made another PR.
#162 
Please review.

**Pull request closed without merging**
