### PR TITLE
Safety Manual Added

### PR DESCRIPTION
**Pull request by anushka1309paul**
Fixes: #230

Description:
Added Women's Safety tips with all required changes.

Checklist:
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by anushka1309paul** [comment]
Kindly check if it is fixed.

**Comment by swapnilsparsh** [comment]
@anushka1309paul Same error.

**Comment by anushka1309paul** [comment]
Kindly send me the error message as I cannot find it.

**Comment by swapnilsparsh** [comment]
120079934-fcfcf200-c0d3-11eb-93de-aa4dadb528ec

**Comment by anushka1309paul** [comment]
I am getting no such error. It must be on your end.

**Comment by anushka1309paul** [comment]
Maybe if you run the check I can know what the error is.

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
1. Align the Questions heading in the center.
2. Remove Expert say from the answer.
3. Reduce the size of the photo and get it aligned with the heading.

**Comment by anushka1309paul** [comment]
If you do not wish to merge this Pull Request kindly say so and then I'll close the issue.

**Comment by anushka1309paul** [comment]
If not, please merge it first, then I shall make another commit with the changes.

**Comment by anushka1309paul** [comment]
The error that is being shown in the checks is nowhere to be found, kindly look into it. Furthermore, I've been assigned to this task for 2 months now and every single time I've made the requested "final" changes  in a single page at that, new changes have been requested each time, which could have easily been pointed out in the very beginning. It is really disappointing to see such a response to the commit I am trying to make but it seems as though this issue is not required in the project at all. If that is the case, I do not wish to spend any more time making unnecessary changes when there is no intention to include this section in the project that in my opinion was unique and empowering when I started to work on it. 
A little more clarity regarding this would have been appreciated.

**Comment by swapnilsparsh** [comment]
> The error that is being shown in the checks is nowhere to be found, kindly look into it. Furthermore, I've been assigned to this task for 2 months now and every single time I've made the requested "final" changes in a single page at that, new changes have been requested each time, which could have easily been pointed out in the very beginning. It is really disappointing to see such a response to the commit I am trying to make but it seems as though this issue is not required in the project at all. If that is the case, I do not wish to spend any more time making unnecessary changes when there is no intention to include this section in the project that in my opinion was unique and empowering when I started to work on it.
> A little more clarity regarding this would have been appreciated.

Sorry for the inconvenience caused.
There is no intention that we don't want to merge your PR but each and every time there are some issues that arise up.
Please resolve the issues which I have mentioned and then I will be merging your PR.

**Pull request closed without merging**
