### PR TITLE
Adding Slides from the backend Admin panel

### PR DESCRIPTION
**Pull request by niksm7**
## Related Issue or bug
  - The issue was that the slideshow was hard coded and required alterations in code on frequent basis which would not follow DRY practices.

Fixes: #221 

#### Describe the changes you've made
The slide show contained direct images of the brave women with their name and content also in the image itself which didn't allow anything to be modified. I have added 2 div tags side by side one with image and the other with name and content which can updated any time. 
The main issue of making the slideshow addition and deletion dynamic was achieved by creating model for the slides by using which any number of slides can be added from the backend and that would display on the frontend.
The responsiveness of the slideshow has also been taken care of.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)

## How Has This Been Tested?

The tests were run to check if the slides were been added and the responsiveness was tested on various devices. As there is new model added please make sure to migrate.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **No model was present**  | <b>Screenshot 2021-03-31 at 12 49 25 AM
 </b> |
Screenshot 2021-03-31 at 12 51 31 AM  | <b>Screenshot 2021-03-31 at 12 52 31 AM
 </b> |

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
slideshow

There is no slide present on the website.

**Comment by niksm7** [comment]
After migrations are made you need to add it from the back-end only then it will show.

**Comment by niksm7** [comment]
As the database is not getting merged I'm providing you the content which you can enter from the backend and it will show up on the frontend:

Slide 1:

**Name**: RUKMINI RAO
**Content**: She founded the Gramya Resource Centre for Women, to tackle various issues of land rights for women, their right to education, prevention of violence against women and girls, etc.
**Read More link** : https://yourstory.com/2015/05/rukmini-rao 
**Image**
ss1


Slide 2:
**Name**: SONAL KAPOOR
**Content**: She founded Protsahan India Foundation, with a vision to eradicate child abuse, by breaking the intergenerational cycle of child abuse and poverty in urban and rural India
**Read More link** : https://www.thebetterindia.com/29118/sonal-kapoor-protsahan/ 
**Image**
ss2

Slide 3:
**Name**: TRISHA SHETTY
**Content**: Trisha Shetty is an activist for gender equity and the founder of SheSays. She is known for human rights advocacy, especially advocating for gender-sensitive policies.
**Read More link** : https://parispeaceforum.org/place/trisha-shetty/
**Image**
ss3

Slide 4:
**Name**: SUNITHA KRISHNAN
**Content**: She is an Indian social activist and chief functionary and co-founder of Prajwala, a non-governmental organization that rescues, rehabilitates and reintegrates sex- trafficked victims into society.
**Read More link** : https://www.vitalvoices.org/people/sunitha-krishnan-2/
**Image**
ss4

Slide 5:
**Name**: LAXMI AGARWAL
**Content**: She is an Indian acid attack survivor, a campaigner for rights of acid attack victims. She was attacked in 2005 in New Delhi at the age of 16. She was the former director of Chhanv Foundation.
**Read More link** :https://www.huffpost.com/archive/in/entry/chhappak-laxmi-agarwal-deepika-padukone-lawyer-acid-attack_in_5e1f5f6ec5b674e44b919c22
**Image**
ss5


I have added content for all the slides here which you can enter in the admin panel.
Do review it @swapnilsparsh

**Comment by niksm7** [comment]
Or if you want should I hard code these 5 slides? @swapnilsparsh

**Comment by swapnilsparsh** [comment]
> After migrations are made you need to add it from the back-end only then it will show. @swapnilsparsh

If user opens the website for first time then there should be some slides present on the website, so if you can then please add the slides that were there before and keep this feature also.

**Comment by niksm7** [comment]
Okay so will hard code these 5 slides with this feature on the back end

**Comment by niksm7** [comment]
Have added the 5 main slides and if required more slides can now be added from the backend admin panel @swapnilsparsh

**Pull request merged**
