### PR TITLE
Added google captcha 

### LINKED ISSUE #232: Add google Captcha
In the login page along with the username and password, we can add google captcha to it. This will make the login page more enhanced and realistic. 
Can you please assign this issue to me. I am a GSSOC'21 participant. 
Thank You

### PR DESCRIPTION
**Pull request by 2001asjad**
Added google captcha in the login page. Attaching ss for demo.
Fixes #232 

###Screenshot:
Captcha ss

### CODE REVIEW

**Comment by sakshikhachane** [comment]
@2001asjad Please resolve the conflicts.

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Add the captcha on register page also
<hr>
**Fix the show password button**


Annotation 2021-04-10 222538

**Comment by sakshikhachane** [comment]
@2001asjad Any updates?

**Comment by 2001asjad** [comment]
> @2001asjad Any updates?

Yeah I made a PR with the changes but it seemed a lot of codebase has changed since I last forked. So I think I'm gonna make a new fork and work on this issue again.

**Pull request closed without merging**
