### PR TITLE
Improved the email format in email.html

### PR DESCRIPTION
**Pull request by coding-geek21**
## Related Issue or bug
  - Improved the format of email 

Fixes: #159 

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |
 
 
 
image

### CODE REVIEW

**Review by sakshikhachane — CHANGES_REQUESTED** [review]
- [ ] Reduce the font size of the list items.
- [ ] Reduce the height of the header and increase the height of the `EMERGENCY!! EMERGENCY!! EMERGENCY!!` box.
- [ ] Can we add the border to the whole content?

**Comment by coding-geek21** [comment]
> * [ ]  Reduce the font size of the list items.
> * [ ]  Reduce the height of the header and increase the height of the `EMERGENCY!! EMERGENCY!! EMERGENCY!!` box.
> * [ ]  Can we add the border to the whole content?

Yes we can add border, I will make other changes too @sakshikhachane

**Comment by coding-geek21** [comment]
image
made changes @sakshikhachane Please review it!

**Review by sakshikhachane — CHANGES_REQUESTED** [review]
Looking good just some minor changes.
- [ ] Reduce the width of the complete message format to 75% or 50%.
- [ ] `Get in touch with as soon as possible`, the header and footer contents all should be aligned to the center.

**Comment by coding-geek21** [comment]
> Looking good just some minor changes.
> 
> * [ ]  Reduce the width of the complete message format to 75% or 50%.
> * [ ]  `Get in touch with as soon as possible`, the header and footer contents all should be aligned to the center.

image
@sakshikhachane  made changes please review it.

**Review by sakshikhachane — APPROVED** [review]

**Comment by coding-geek21** [comment]
@swapnilsparsh @sakshikhachane Please add the level tag

**Pull request merged**
