### PR TITLE
Update CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by Akshu-on-github**
As requested in issue #48

**Changes made:**
- Added the details of two contributors to CONTRIBUTORS.md
- Updated the icons to the best of my knowledge
- Copied the table to README.md

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Move the table under the Our Contributors Heading.

**Comment by Akshu-on-github** [comment]
For some reason, the table remained at the end though I moved the code appropriately... So I moved the heading down instead. Please take a look @swapnilsparsh

**Comment by swapnilsparsh** [comment]
> For some reason, the table remained at the end though I moved the code appropriately... So I moved the heading down instead. Please take a look @swapnilsparsh

Don't move the whole contributors section to the end of README.md file 
Keep the Contributors sections where it was earlier and there only place your table.

**Comment by Akshu-on-github** [comment]
> > For some reason, the table remained at the end though I moved the code appropriately... So I moved the heading down instead. Please take a look @swapnilsparsh
> 
> Don't move the whole contributors section to the end of README.md file
> Keep the Contributors sections where it was earlier and there only place your table.

Done 👍

**Comment by Akshu-on-github** [comment]
Thanks a bunch!

**Pull request merged**
