### PR TITLE
fixed the extra white space below carousel

### PR DESCRIPTION
**Pull request by saaiswetha**
## Related Issuse or bug
  - bug: extra space below carousel in homepage.

Fixes: #103 

#### Describe the changes you've made
I've changed the dimensions of margin of footer from the carousel. This removes the extra white space caused due to 'auto' margin.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
**Fix this**
x

**Comment by saaiswetha** [comment]
@swapnilsparsh Shall I limit the web pg height ? Or increase the footer length?

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh Shall I limit the web pg height ? Or increase the footer length?

Don't increase the footer length, you can try by doing some changes in carousel.

**Comment by sakshikhachane** [comment]
Hey @saaiswetha,
Any updates? Are you able to do the changes?

**Comment by saaiswetha** [comment]
> Hey @saaiswetha,
> Any updates? Are you able to do the changes?

I tried to modify the carousel length but its overfitting the pg. But I checked mobile preview also, there are no extra white spaces below carousel.
space2

**Comment by sakshikhachane** [comment]
> **Fix this**
> x

Because of the changes you made, there are no extra white spaces below the carousel. But there is extra white space below the footer. Please have a look.

**Comment by saaiswetha** [comment]
> > **Fix this**
> > x
> 
> Because of the changes you made, there are no extra white spaces below the carousel. But there is extra white space below the footer. Please have a look.

Yeah I got it. I've fixed that now, could you check it out.

**Comment by saaiswetha** [comment]
@sakshikhachane Yeah got it. I've fixed that now, could you check it out.

**Review by sakshikhachane — CHANGES_REQUESTED** [review]
1. The font-size of the footer and also of `WONDER WOMEN OF INDIA` is changed. Please make the size the same as the previous size.
2. The gif image at the top is going inside the navbar. Check the image for reference. Please fix it.
r1

**Comment by saaiswetha** [comment]
space

1.  The font size is enlarged with respect to different previews , if I try to keep the size fixed a space below footer is coming.
     Not able to do both i.e keep the font size fixed and avoid the space below footer.  (the font size can be kept fixed using 
     initial scale tag but this causes space below footer).
   
2.  You can try scrolling down, gif is not going inside navbar.

**Comment by sakshikhachane** [comment]
Hey @saaiswetha,
I have checked it again, the gif is going inside the navbar. Please fix it.

**Pull request closed without merging**
