### PR TITLE
welcome bot added

### PR DESCRIPTION
**Pull request by Ankita297**
## Related Issue or bug
A github action to greet contributor on opening his/her first PR or first issue .

Fixes: #273 

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Type of change

Please delete options that are not relevant.

- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [x ] Code style update (formatting, local variables)
- [ x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ x] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [ x] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ x] I have made corresponding changes to the documentation.
- [ x] My changes generate no new warnings.
- [ x] I have added tests that prove my fix is effective or that my feature works.
- [ x] New and existing unit tests pass locally with my changes.
- [ x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |
 
 
 
 
New issue · Issue #1 · Ankita297_Story - Google Chrome 22-04-2021 00_53_11

### CODE REVIEW

**Comment by Ankita297** [comment]
@swapnilsparsh @sakshikhachane Please review my PR .

**Comment by sakshikhachane** [comment]
This message will be displayed only after the first PR is opened right?

**Comment by Ankita297** [comment]
Yes @sakshikhachane .

**Comment by Ankita297** [comment]
Yes and also after first issue is opened

**Comment by sakshikhachane** [comment]
Write `Welcome to the community!` first followed by the rest of the message. Add emojis as well.

**Comment by Ankita297** [comment]
Okay I will do it .

**Comment by Ankita297** [comment]
@sakshikhachane done . Please see it now .

**Pull request merged**
