### PR TITLE
Added the option to call the mentioned helpline number on clicking the phone icon in helpline_numbers.html

### PR DESCRIPTION
**Pull request by kanishka8276**
## Related Issuse or bug
  - Info about Issue or bug
#125
Fixes: #[issue number that will be closed through this PR]

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!
I have added the links in the phone icons to the helpline numbers so that when they are clicked the call is made to those helpline numbers.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Ran the page in the localhost and tried using the link to call. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.
NA
## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

  
Screenshot (61)

### CODE REVIEW

**Comment by sakshikhachane** [comment]
Hey @kanishka8276,
Good work! Just remove the files which are not relevant to this PR. 
I guess the files from [#135](https://github.com/swapnilsparsh/Rescue/pull/135) have been merged into this. 
If you need any kind of help, so tell me:)

**Comment by kanishka8276** [comment]
@sakshikhachane  Please help me with this. For this issue I created a separate PR. And used git add helpline_numbers.html to add only this file. I don't know why it's including all the previous commits.

**Comment by sakshikhachane** [comment]
@kanishka8276 This might have happened because you have created the branch `callicon` on the top of the branch `kanishka` which is for PR number 135.

**Comment by kanishka8276** [comment]
Ok! 
Once the previous PR is merged there won't be any issue with this I think.
Or should I create another PR by creating another branch?

**Comment by sakshikhachane** [comment]
@kanishka8276 Please make another PR.

**Comment by kanishka8276** [comment]
> @kanishka8276 Please make another PR.

Ok sure!

**Pull request closed without merging**
