### PR TITLE
Improved women right

### PR DESCRIPTION
**Pull request by Harsh-bartariya**
i have update some more legislations and rights related with women and i have add some links and images also. Please merge it.

### CODE REVIEW

**Comment by swapnilsparsh** [comment]
There was no issue regarding this problem.
So this PR is invalid.
@Harsh-bartariya

**Comment by Harsh-bartariya** [comment]
But sir there is a issue mentioned that improve the documentation regarding women's law section....kindly explain it maybe i haven't got you.

**Comment by swapnilsparsh** [comment]
@Harsh-bartariya Issue is opened for Women's Safety Law section #4 and you have requested a PR for Women's Right Section whose issue has been closed.
Kindly clear your confusion and make a valid PR

**Comment by Harsh-bartariya** [comment]
sir ok i understand , kindly do a help , please tell me did i update wrong file ? i mean i didn't see any file named women's safty laws section, should i improve the main readme documentation or there is something inside the website. last night i really work hard sor for collecting the laws. kindly make it clear my doubt so i can do my pr.

**Comment by swapnilsparsh** [comment]
@Harsh-bartariya 
I appreciate your hard work.
You have to make changes in women's_law.html file according to the issue that is assigned  to you.

**Comment by Harsh-bartariya** [comment]
Thank you sir ,now it's clear sir i'll make a PR asap,
@swapnilsparsh 
wish you a very happy new year in advance sir.

**Pull request closed without merging**
