### PR TITLE
Modifications : Issue#178

### PR DESCRIPTION
**Pull request by SUMEKAGARWAL**
Fixes: #178 
**Modified changes :**
1. Hovering issue in womens_rights.html.
2. Committed "YES" or "NO" change in delete_contact.html
3. Elements in threads of "Emergency Contact " page are not accurately assigned...so did that!
4. Edited the footer sentence.
5. Below emergency contacts, sentence modification.

### CODE REVIEW

**Comment by SUMEKAGARWAL** [comment]
@swapnilsparsh @sakshikhachane 
Have a look on these changes. If something is not up to the mark, please update the change that have to be committed.  
And if not, merge my PR.

**Comment by SUMEKAGARWAL** [comment]
@swapnilsparsh @sakshikhachane
Have a look on these changes. If something is not up to the mark, please update the change that have to be committed.
And if not, merge my PR.

**Review by sakshikhachane — CHANGES_REQUESTED** [review]
Please remove the following files -
- [ ] mail.py
- [ ] 0001_initial.py
- [ ] common.html
- [ ] home.html

The `common.html` and `home.html` files are to be removed because the footer is already redesigned and it will cause unnecessary conflicts.

**Comment by SUMEKAGARWAL** [comment]
@sakshikhachane @swapnilsparsh 
I have deleted the listed commits. Is it fine now?

**Comment by SUMEKAGARWAL** [comment]
It is done! Please have a look on my PR.

**Review by sakshikhachane — CHANGES_REQUESTED** [review]
@SUMEKAGARWAL You have to revert the changes that you have done. Don't delete the files.
Also, resolve the conflicts.

**Comment by SUMEKAGARWAL** [comment]
@sakshikhachane How to again revert back commits?
Could you please guide me through this?

**Comment by SUMEKAGARWAL** [comment]
Hello @*sakshikhachane, *
*I am still super confused whether to put all the changes that I made
during my first commit intact or should I delete the changes in common.html
and home.html as you said those are already in action.*
*Please acknowledge me about this issue as soon as possible.*
*Thank you. Regards *

**Comment by SUMEKAGARWAL** [comment]
Good morning  @*sakshikhachane,*
*Could you please have a look into the above message.*
*Its a request.*
*Thank you! Regards*

**Comment by SUMEKAGARWAL** [comment]
Hello @sakshikhachane ,
Could you please tell me what changes that I need to make now clearly.

**Comment by swapnilsparsh** [comment]
> Hello @sakshikhachane ,
> Could you please tell me what changes that I need to make now clearly.

What problem are you facing, can you please explain ?

**Comment by sakshikhachane** [comment]
The PR #212 is of the same issue I think. So, I am closing this PR.

**Pull request closed without merging**
