### PR TITLE
Safety Manual added

### PR DESCRIPTION
**Pull request by anushka1309paul**
Fixes: #230

Description:
Added Women's Safety tips with all required changes.

Checklist:
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Few changes:
1. Change the heading image with some good image.
2. Remove the png from the heading that is there at the last.
3. Make a Question as a heading and remove the question from all the headings.

**Comment by anushka1309paul** [comment]
Kindly let me know if there are any further changes to be made. I'll make
all of them at the same time instead of doing minor changes repeatedly.

**Comment by anushka1309paul** [comment]
Sir, a few images that can be used for the heading are in the drive link below :

https://drive.google.com/drive/folders/1ZtP6O0j2St_jrw8gdUKLRZDDhdscbQcB?usp=sharing

Kindly go through the same and let me know which one to use .

**Comment by swapnilsparsh** [comment]
> Sir, a few images that can be used for the heading are in the drive link below :
> 
> https://drive.google.com/drive/folders/1ZtP6O0j2St_jrw8gdUKLRZDDhdscbQcB?usp=sharing
> 
> Kindly go through the same and let me know which one to use .

2nd photo without bg.

**Pull request closed without merging**
