### PR TITLE
Improved footer

### PR DESCRIPTION
**Pull request by jatinjain001**
I improved footer with amazing features please check it and let me know how it is .

### CODE REVIEW

**Comment by jatinjain001** [comment]
@swapnilsparsh check it please

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Annotation 2021-01-10 234111
1. Remove the things which I have mentioned in the above picture.
2. Keep only Developers heading as about us and developers are on the same page so no need of making two different heading for one same page.
3. Make the footer more slimmer.

else everything is fine.

**Comment by jatinjain001** [comment]
So it will be just like before..

**Comment by swapnilsparsh** [comment]
> okay I will do.
> foo

Perfect

**Comment by jatinjain001** [comment]
Changes done, You can merge it now.

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Annotation 2021-01-12 233135

There are extra white space on both the sides i.e vertically and horizontally

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Still there is extra white space horizontally below the footer
Vertical white space has been resolved.

**Comment by jatinjain001** [comment]
I tried but in login page we will get additional spaces . if we do that thing then footer size height will be more

**Pull request merged**
