### PR TITLE
Contact

### PR DESCRIPTION
**Pull request by mansijain980**
Fixes: #157

### CODE REVIEW

**Comment by mansijain980** [comment]
@swapnilsparsh i have requested a new PR from branch "contact " got the issue #157 .
Please review it.

**Comment by swapnilsparsh** [comment]
@mansijain980 You have opened two PR regarding this issue, kindly close one issue in order to get your PR merged.

**Comment by swapnilsparsh** [comment]
@mansijain980  There are some issues while running your code, please resolve it.

**Comment by mansijain980** [comment]
> @mansijain980 There are some issues while running your code, please resolve it.

@swapnilsparsh please close this pr and i will request a fresh PR so that all issues get resolved.

**Pull request closed without merging**
