### PR TITLE
fixed errors in placing confidential info

### PR DESCRIPTION
**Pull request by harshakhmk**
## Related Issue or bug
  - place all the confidential information in .env file

Fixes: #[292](https://github.com/swapnilsparsh/Rescue/issues/292)

#### Describe the changes you've made
Moved all the confidential information into environment variables and sending mail when the email and password provided by the host is Not None thereby reducing latency on the SMTPLIB server
Used python decouple module with version 3.4 to configure the environment variables

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by harshakhmk** [comment]
@swapnilsparsh  review it, is working fine now

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
There are some bug errors while running your code, resolve them.

**Comment by harshakhmk** [comment]
> There are some bug errors while running your code, resolve them.

You need to install python-decouple module
Could you exactly mention what errors are you facing in the screenshot

**Comment by harshakhmk** [comment]
I have updated my branch with all latest changes in master, I guess it won't have any issues now

**Comment by swapnilsparsh** [comment]
Resolve the conflicts

**Comment by harshakhmk** [comment]
> Resolve the conflicts

I have updated my commits, have a look

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
ss

Resolve it

**Comment by harshakhmk** [comment]
I didn't get any such errors on my local branches
no-issues
everything is running fine for both my branch, master(both updated)
Also, I didn't change anything in migrations scripts and all so my branch shouldn't be getting such errors, as long as you delay, I need to keep on updating my branch to make it in sync with the master

**Comment by swapnilsparsh** [comment]
ss
I am getting this error

**Comment by harshakhmk** [comment]
U were not in virtual env, activate your virtual env and pull the latest commit from my branch then try the same

**Comment by swapnilsparsh** [comment]
> U were not in virtual env, activate your virtual env and pull the latest commit from my branch then try the same

I have done the same still this error is showing.

**Comment by harshakhmk** [comment]
> > U were not in virtual env, activate your virtual env and pull the latest commit from my branch then try the same
> 
> I have done the same still this error is showing.

Have u installed all pip requirements in virtual env, I have added extra package ```python-decouple```, run ```pip install -r requirements.txt ``` again in this branch and can you tell me by invoking which view u r getting this error or you are getting this error by loading the main page itself
I am sure, the 
no-issues-part2
error is not from my side, I have recently tested the code, check on your side

**Comment by swapnilsparsh** [comment]
> > > U were not in virtual env, activate your virtual env and pull the latest commit from my branch then try the same
> > 
> > 
> > I have done the same still this error is showing.
> 
> Have u installed all pip requirements in virtual env, I have added extra package `python-decouple`, run `pip install -r requirements.txt ` again in this branch and can you tell me by invoking which view u r getting this error or you are getting this error by loading the main page itself
> I am sure, the
> no-issues-part2
> error is not from my side, I have recently tested the code, check on your side

I have done everything but don't know why this problem is happening.
I have checked everything on my end and it's working absolutely fine, but running your code gives me an error.

**Comment by harshakhmk** [comment]
can u paste the last part of error message, it is not visible

**Comment by harshakhmk** [comment]
You need to add all variables that I mentioned in the .env file and also your google reCAPTCHA secret key too

**Comment by swapnilsparsh** [comment]
> You need to add all variables that I mentioned in the .env file and also your google reCAPTCHA secret key too

Done it already.

**Comment by harshakhmk** [comment]
> > You need to add all variables that I mentioned in the .env file and also your google reCAPTCHA secret key too
> 
> Done it already.

I don't understand why you are getting those errors, everything is perfect from my side
 Putting in a lot of effort and then failing to merge a PR is a little painful and all the hard work that I put in goes in vain

**Comment by swapnilsparsh** [comment]
> > > You need to add all variables that I mentioned in the .env file and also your google reCAPTCHA secret key too
> > 
> > 
> > Done it already.
> 
> I don't understand why you are getting those errors, everything is perfect from my side
> Putting in a lot of effort and then failing to merge a PR is a little painful and all the hard work that I put in goes in vain

I am trying my level best to resolve the error as you have invested your time and hard work in this issue and due to some bug, it is not possible to merge the PR.

**Comment by harshakhmk** [comment]
> > > > You need to add all variables that I mentioned in the .env file and also your google reCAPTCHA secret key too
> > > 
> > > 
> > > Done it already.
> > 
> > 
> > I don't understand why you are getting those errors, everything is perfect from my side
> > Putting in a lot of effort and then failing to merge a PR is a little painful and all the hard work that I put in goes in vain
> 
> I am trying my level best to resolve the error as you have invested your time and hard work in this issue and due to some bug, it is not possible to merge the PR.

can you reshare the last part of the error screenshot

**Comment by swapnilsparsh** [comment]
> > > > > You need to add all variables that I mentioned in the .env file and also your google reCAPTCHA secret key too
> > > > 
> > > > 
> > > > Done it already.
> > > 
> > > 
> > > I don't understand why you are getting those errors, everything is perfect from my side
> > > Putting in a lot of effort and then failing to merge a PR is a little painful and all the hard work that I put in goes in vain
> > 
> > 
> > I am trying my level best to resolve the error as you have invested your time and hard work in this issue and due to some bug, it is not possible to merge the PR.
> 
> can you reshare the last part of the error screenshot
> are u getting this error on running `manage.py runserver` ?

The photo which I shared with you above is the only error that I am getting and it's a full photo.
I am getting this error while running python manage.py migrate.

**Comment by harshakhmk** [comment]
see if this helps https://stackoverflow.com/questions/39581579/django-migrations-gives-error-when-run-separately-in-different-machines
https://stackoverflow.com/questions/61658637/getting-errors-while-trying-to-run-manage-py-migrate

**Comment by swapnilsparsh** [comment]
> see if this helps https://stackoverflow.com/questions/39581579/django-migrations-gives-error-when-run-separately-in-different-machines
> https://stackoverflow.com/questions/61658637/getting-errors-while-trying-to-run-manage-py-migrate

Tried all these things but still issue didn't resolve.

**Comment by harshakhmk** [comment]
> > see if this helps https://stackoverflow.com/questions/39581579/django-migrations-gives-error-when-run-separately-in-different-machines
> > https://stackoverflow.com/questions/61658637/getting-errors-while-trying-to-run-manage-py-migrate
> 
> Tried all these things but still issue didn't resolve.

send me the bottom part of the error that you were getting after scrolling down to the bottom
Can you delete the whole branch and the code of this feature branch and try pulling it again, something got messed up with migrations

**Comment by swapnilsparsh** [comment]
> > > see if this helps https://stackoverflow.com/questions/39581579/django-migrations-gives-error-when-run-separately-in-different-machines
> > > https://stackoverflow.com/questions/61658637/getting-errors-while-trying-to-run-manage-py-migrate
> > 
> > 
> > Tried all these things but still issue didn't resolve.
> 
> send me the bottom part of the error that you were getting after scrolling down to the bottom
> Can you delete the whole branch and the code of this feature branch and try pulling it again, something got messed up with migrations

Already told you that the photo which I shared with you is the complete photo with error.
You can try recommitting the code.

**Comment by harshakhmk** [comment]
> > > > see if this helps https://stackoverflow.com/questions/39581579/django-migrations-gives-error-when-run-separately-in-different-machines
> > > > https://stackoverflow.com/questions/61658637/getting-errors-while-trying-to-run-manage-py-migrate
> > > 
> > > 
> > > Tried all these things but still issue didn't resolve.
> > 
> > 
> > send me the bottom part of the error that you were getting after scrolling down to the bottom
> > Can you delete the whole branch and the code of this feature branch and try pulling it again, something got messed up with migrations
> 
> Already told you that the photo which I shared with you is the complete photo with error.
> You can try recommitting the code.

You were not understanding what I meant, ok leave it trying deleting the codebase in this branch and pull it again

**Comment by swapnilsparsh** [comment]
> > > > > see if this helps https://stackoverflow.com/questions/39581579/django-migrations-gives-error-when-run-separately-in-different-machines
> > > > > https://stackoverflow.com/questions/61658637/getting-errors-while-trying-to-run-manage-py-migrate
> > > > 
> > > > 
> > > > Tried all these things but still issue didn't resolve.
> > > 
> > > 
> > > send me the bottom part of the error that you were getting after scrolling down to the bottom
> > > Can you delete the whole branch and the code of this feature branch and try pulling it again, something got messed up with migrations
> > 
> > 
> > Already told you that the photo which I shared with you is the complete photo with error.
> > You can try recommitting the code.
> 
> You were not understanding what I meant, ok leave it trying deleting the codebase in this branch and pull it again

Still showing the same error.

**Comment by khanfarhan10** [comment]
@harshakhmk conflicts still exist.

**Comment by harshakhmk** [comment]
Btw which OS were you using @swapnilsparsh

**Comment by swapnilsparsh** [comment]
> Btw which OS were you using @swapnilsparsh

Windows

**Pull request closed without merging**
