### PR TITLE
Location Details for SOS Sent to Nearest Police Station #239

### LINKED ISSUE #239: Location Details for SOS Sent to Nearest Police Station
- Broadcast Message to nearest located/prementioned Police Station

### PR DESCRIPTION
**Pull request by iaryangoyal**
Created a form for location to be filled by user .
Fixes #239 
If there is any issue please let me know

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
After filling the form ,location details should go to nearest Police Statio when clicking on emergency button

**Comment by iaryangoyal** [comment]
okie wait let me make changes

**Comment by iaryangoyal** [comment]
I have done some changes please check

**Comment by khanfarhan10** [comment]
You also need to add this to the Django backend application.

**Comment by iaryangoyal** [comment]
okie wait let me do that

**Comment by iaryangoyal** [comment]
Can you guide me with the django part?

**Comment by swapnilsparsh** [comment]
> Can you guide me with the django part?

Have you ever worked on django before ?

**Comment by iaryangoyal** [comment]
No not any official task but i can try

**Comment by swapnilsparsh** [comment]
> No not any official task but i can try

@khanfarhan10 Can you please look into this ?

**Comment by iaryangoyal** [comment]
guide me if possible otherwise give me some HTML CSS task i will do.

**Comment by iaryangoyal** [comment]
I am a GSSOC participant

**Comment by sakshikhachane** [comment]
@khanfarhan10 Can you please look into this?

**Comment by khanfarhan10** [comment]
> @khanfarhan10 Can you please look into this?

Can you assign someone? Multiple People were interested I guess.

**Pull request closed without merging**
