### PR TITLE
Modified the config.yml file for Welcome Bot

### PR DESCRIPTION
**Pull request by m-code12**
Fixes: #85 

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by m-code12** [comment]
@swapnilsparsh Please review and merge this pr.

**Comment by m-code12** [comment]
> @swapnilsparsh Please review and merge this pr.

@swapnilsparsh

**Comment by m-code12** [comment]
Also, please update my points on the leaderboard

**Comment by swapnilsparsh** [comment]
> Also, please could you update my points on the leaderboard @swapnilsparsh .

It will get updated automatically after some time.

**Pull request merged**
