### PR TITLE
Safety Manual Added

### PR DESCRIPTION
**Pull request by anushka1309paul**
- Necessary changes in layout of Safety manual made

### CODE REVIEW

**Comment by sakshikhachane** [comment]
@anushka1309paul Always link the issue for which the PR is created.

**Review by sakshikhachane — CHANGES_REQUESTED** [review]
- [ ] `General Guidelines` etc other collapsible parts are getting merged with the image. Increase space between them.
- [ ] For the contents in the accordions parts keep it the same as that of `Women Safety laws`. Remove background color.
- [ ] For the `Specific Situations` part, make all the questions in accordion format just like `General guidelines`. Keep the structure the same as that of the `Women Safety Laws page`.
- [ ] For the `Self Defence Tips` part keep videos in the form of a grid (2*3). Reduce the width and height of the video. 
- [ ] Keep some considerable space between the `General Guidelines`, the `Specific Situations` the `Self Defence Tips` part.

**Comment by anushka1309paul** [comment]
Ma'am, could you explain the first point of the changes requested? I'm not finding any merging of images. In case you mean that the image is to the left and text is on the right, that is how I meant it to look like, if that needs to be changed, please clarify the same, and I shall make the necessary changes.

**Comment by sakshikhachane** [comment]
@anushka1309paul I am talking about this image. Add some space between the image and the text.
image

**Comment by anushka1309paul** [comment]
Ok Ma'am, I will fix that.

**Comment by anushka1309paul** [comment]
The necessary changes have been made, kindly go through the same.

**Comment by swapnilsparsh** [comment]
@anushka1309paul There are some files that are creating conflicts, please rebase your code with the origin.

**Pull request closed without merging**
