### PR TITLE
added change password page

### PR DESCRIPTION
**Pull request by coding-geek21**
## Added change password page 
  - Info about Issue or bug

Fixes: #197 

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

- Added change password functionality 
- User can click on the username in navbar and select change password  to change their password after login
- added Illustration and UI as same as register page

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |
 
 
 
 

https://user-images.githubusercontent.com/53329034/115589966-14370b80-a2ee-11eb-9bd7-dfd446971e7d.mp4

### CODE REVIEW

**Comment by coding-geek21** [comment]
@swapnilsparsh please review this PR.

**Review by sakshikhachane — CHANGES_REQUESTED** [review]
- [ ] For the text `Your old password was entered incorrectly. Please enter it again.`, make an alert box with red background.
- [ ] When logged in through a google account, the password shouldn't be changed. Add this on that page.

**Comment by coding-geek21** [comment]
> Good work! Just some minor changes.
> 
> * [ ]  For the text `Your old password was entered incorrectly. Please enter it again.`, make an alert box with red background.
> * [ ]  When logged in through a google account, the password shouldn't be changed. Add this on that page.

@sakshikhachane  Made the requested changes for now the alert messages is displayed in blue color , which will be changed in the issue #281, there i will make changes to red color 



https://user-images.githubusercontent.com/53329034/116785227-08013a00-aab6-11eb-9b3d-1293ef049bf7.mp4

**Review by sakshikhachane — CHANGES_REQUESTED** [review]
I am facing this error whenever I am trying to log in through a google account. Please fix this.
image

**Comment by coding-geek21** [comment]
> I am facing this error whenever I am trying to log in through a google account. Please fix this.
> image

There is some issues in this pull request so i have created a new PR #287  please check that @sakshikhachane

**Pull request closed without merging**
