### PR TITLE
Changes In Navbar as per issue #119

### LINKED ISSUE #119: Improving the navbar
I would like to improve the appearance of the navbar by making it more attractive and relocating the links in a better way. Contributing as a participant of GSSOC'21. Could you please assign it to me?

### PR DESCRIPTION
**Pull request by prisha-srivastava**
#### Describe the changes you've made
I have slightly changed the appearance of the navigation bar. I changed the EMERGENCY link to a button , changed the location of the navlinks and changed colour of the navbar. fixes #119 

## Screenshots

 Original    
 image
Updated
 image

### CODE REVIEW

**Comment by swapnilsparsh** [comment]
**Fix all the issues:**

Use same colour in navbar and dropdown
Color

On clicking the emergency contact without loging in it showing the error
Emergency Contact

On clicking the emergency without loging in it showing the error
emergency

On hovering the emergency button white colour gets mixed
hover

**Comment by prisha-srivastava** [comment]
I have made the necessary changes in the recent commit. 
Attaching a GIF for your reference. In my browser, it is not showing an error on clicking the emergency button without logging in. You can check.

**Comment by swapnilsparsh** [comment]
@prisha-srivastava 
1. Align the text in center
center

2. Change the colour when hovering the dropdown and other headings in navbar.

**Else everything is fine**

**Comment by prisha-srivastava** [comment]
Made the final changes. Please check the final commit.
127 0 0 1_8000_home_

**Comment by sakshikhachane** [comment]
I think we can shift `CLICK IF IN EMERGENCY` button after `Emergency contacts`. What do you think @swapnilsparsh?

**Comment by sakshikhachane** [comment]
@prisha-srivastava Please mention which issue do this PR fixes as well in the PR.

**Comment by prisha-srivastava** [comment]
@sakshikhachane Done.

**Comment by sakshikhachane** [comment]
> I think we can shift `CLICK IF IN EMERGENCY` button after `Emergency contacts`.

Do this and rename `CLICK IF IN EMERGENCY` to `EMERGENCY`.

**Comment by prisha-srivastava** [comment]
@sakshikhachane Done.
image

**Comment by sakshikhachane** [comment]
> @sakshikhachane Done.
> image

Just reduce the width of the button then it is ready to be merged. :)

**Comment by prisha-srivastava** [comment]
I hope it looks better now.
image

**Comment by sakshikhachane** [comment]
> I hope it looks better now.
> image


Yes, it looks good. Keep the navbar the same even after logging in. You have removed the rest of the links on the navbar. Please add it.

**Comment by prisha-srivastava** [comment]
@sakshikhachane Which links are you specifically talking about. All the links are present.

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
x

1. Keep the navbar the same even after logging in. You have removed the rest of the links on the navbar. Please add it.
2. Add a dropdown arrow infront of User (More is having dropdown arrow)

**Comment by prisha-srivastava** [comment]
@swapnilsparsh @sakshikhachane 
Made the changes. Kindly check

https://user-images.githubusercontent.com/63402702/111021737-831e6c00-83f4-11eb-84e4-90f2aa7dfd9d.mp4

**Comment by sakshikhachane** [comment]
Hey @prisha-srivastava,
Please resolve the conflicts.

**Comment by prisha-srivastava** [comment]
@sakshikhachane Resolved the conflicts.

**Comment by sakshikhachane** [comment]
@prisha-srivastava Please fix the `helpline_numbers` page. It is distorted.

**Comment by prisha-srivastava** [comment]
> @prisha-srivastava Please fix the `helpline_numbers` page. It is distorted.

The page is loading perfectly on my browser. Can you tell me where the problem is. I can't seem to find it.

**Comment by prisha-srivastava** [comment]
> @prisha-srivastava Please fix the `helpline_numbers` page. It is distorted.

Done. Is there anything else to be done?

**Comment by swapnilsparsh** [comment]
> > @prisha-srivastava Please fix the `helpline_numbers` page. It is distorted.
> 
> Done. Is there anything else to be done?

Everythig is fine, you have to just resolve the conflicts and then it is ready to merge.

**Comment by prisha-srivastava** [comment]
@swapnilsparsh Resolved all conflicts.

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
**Fix** - After opening the More dropdown, its not collaping when clicking on it again.

**Comment by prisha-srivastava** [comment]
> **Fix** - After opening the More dropdown, its not collaping when clicking on it again.

I have fixed it. Please tell me if anything else is still missing.

**Pull request merged**
