### PR TITLE
Update Automessage

### PR DESCRIPTION
**Pull request by mansijain980**
## Related Issue or bug
  Github bot bug

Fixes: #294 

#### Description
Updated the message on closing the issue.

### CODE REVIEW

**Comment by swapnilsparsh** [comment]
@mansijain980 Resolve the conflicts.

**Comment by mansijain980** [comment]
image
there is only 1 file "automessage.yml" which is having conflict .

**Comment by mansijain980** [comment]
image

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
You don't have to change the message, you just have to add the condition if the pr is closed then there should be another message rather than what it is now.

**Comment by mansijain980** [comment]
image
sir in this code , there is already a condition that when PR is closed it will show " response:  ** "This issue is closed @${{ github.event.pull_request.user.login }}. Looking forward for your contributions :)" ** this message .

**Comment by swapnilsparsh** [comment]
> image
> sir in this code , there is already a condition that when PR is closed it will show " response: **This issue is closed @${{ github.event.pull_request.user.login }}. Looking forward for your contributions :)** this message .

The message will prompt when PR is merged so you have to make changes when pr is closed.

**Comment by mansijain980** [comment]
image
we can perform only these actions on workflow nd for the type closed there is already a message . i think we should add a type removed so then when pr will be deleted . there will be some anothwr msg.

**Comment by swapnilsparsh** [comment]
> image
> @swapnilsparsh we can perform only these actions on workflow nd for the type closed there is already a message . i think we should add a type removed so then when pr will be deleted . there will be some anothwr msg.

Add it.

**Pull request closed without merging**
