### PR TITLE
Added Image Gallery

### PR DESCRIPTION
**Pull request by mansijain980**
Fixes: #220 

#### Describe the changes you've made
Added an option in navbar "image gallery" in home page .
Image gallery contains reports of 2020 and female rights activists with their descriptions .

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist: 
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |
 
image
image
image

### CODE REVIEW

**Comment by jatiinyadav** [comment]
Screenshot (34)
Hey @mansijain980, fix this.

**Comment by mansijain980** [comment]
image
I am getting error on adding gallery.html url on  **line 16** this.
Please tell me what is the issue?
image

Before adding line 16 it was properly working . 
Thanks.

**Comment by mansijain980** [comment]
image
Now its working fine after removing line 16 from urls.py

**Comment by mansijain980** [comment]
I have done all changes required to run this image gallery in home.html , urls.py , viwes.py , gallery.html.
Please check it.
Thanks.

**Comment by jatiinyadav** [comment]
Screenshot (36)

Hey @mansijain980, Fix this issues mentioned below
1. Align the cards in a proper manner.
2. Use the same font as used in the website.
3. The back to top button should be same.
4. Add header and footer.
5. Use good quality pictures. (Don't stretch the pictures)

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Use some good quality pics
Many photos are stretching, fix it.
Use proper css for making the page look good.

**Comment by mansijain980** [comment]
> Use soe good quality pics
> Many photos are stretching, fix it.
> Use proper css for making the page look good.

yes sir i m adding footer etc as well .

**Comment by mansijain980** [comment]
Please check login.html page and let me know.
Thanks

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Header and footer is not there
Link this page to common.html to get the header and foote
Fix the photos which are stretching
Some photos are missing in the table and details also.

**Comment by swapnilsparsh** [comment]
@sakshikhachane Can you please look into this as there is no proper use of css as she is using only html.

**Comment by mansijain980** [comment]
> > Use soe good quality pics
> > Many photos are stretching, fix it.
> > Use proper css for making the page look good.
> 
> yes sir i m adding footer etc as well .

yes sir i will do this as i noticed it after commiting.

**Comment by mansijain980** [comment]
> @sakshikhachane Can you please look into this as there is no proper use of css as she is using only html.

Maam wherever needed i used it , i will do changes .
Thanks.

**Comment by mansijain980** [comment]
> Please check login.html page and let me know.
> Thanks

?

**Comment by swapnilsparsh** [comment]
> > @sakshikhachane Can you please look into this as there is no proper use of css as she is using only html.
> 
> Maam wherever needed i used it , i will do changes .
> Thanks.

Please look after the other pages that are there on the website and use the CSS accordingly.

**Comment by mansijain980** [comment]
@swapnilsparsh sir , actually i have assigned three issues of this repo and out of three i did commit for two bt it does not make a new pull request and everytime the changes were commit on a frst pull request i did . 
Can u see to it?
Thanks.

**Comment by sakshikhachane** [comment]
> @swapnilsparsh sir , actually i have assigned three issues of this repo and out of three i did commit for two bt it does not make a new pull request and everytime the changes were commit on a frst pull request i did .

@mansijain980 If you are working on different issues then always make sure that all the work that is done is on different branches which must not be the `master` branch.

**Comment by mansijain980** [comment]
> > @swapnilsparsh sir , actually i have assigned three issues of this repo and out of three i did commit for two bt it does not make a new pull request and everytime the changes were commit on a frst pull request i did .
> 
> @mansijain980 If you are working on different issues then always make sure that all the work that is done is on different branches which must not be the `master` branch.
> I think you should close all the PRs you have made and make new and clean PRs so that we can review them properly and your problem will be resolved.

thanks

**Comment by sakshikhachane** [comment]
@mansijain980 Any updates?

**Comment by sakshikhachane** [comment]
Hey @mansijain980,
It's 1 month since you have created the issue and 18 days since you have created the PR. We can't wait for such a long time as there are many participants you want to contribute. So, I am closing this PR.

**Pull request closed without merging**
