### PR TITLE
Added password reset functionality to login page - issue #189

### PR DESCRIPTION
**Pull request by coding-geek21**
## Related Issue or bug
  - Added password reset functionality to login page by sending email to the user using their registered email and enable them to reset password

Fixes: #189 

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |
 
image
 
image

image

image

image

### CODE REVIEW

**Comment by coding-geek21** [comment]
Hi @sakshikhachane  I had completed this issue , Please review it!

in settings,py   Email and password of that email from which you wish to send password reset mail to user should be updated

image

please check with it and tell me if there are any changes to do :)

**Comment by swapnilsparsh** [comment]
@coding-geek21 I will review this PR in 1-2 days.

**Comment by coding-geek21** [comment]
> @coding-geek21 I will review this PR in 1-2 days.

Ok @swapnilsparsh

**Comment by swapnilsparsh** [comment]
> > @coding-geek21 I will review this PR in 1-2 days.
> 
> Ok @swapnilsparsh

There are some bugs which you have to fix.
Fix it and then commit again.

**Comment by coding-geek21** [comment]
@swapnilsparsh  made changes and fixed bugs also resolved conflicts please review it

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh made changes and fixed bugs also resolved conflicts please review it

While checking your PR I was Not able to reset my password, can you tell me how this works ?

**Comment by coding-geek21** [comment]
> > @swapnilsparsh made changes and fixed bugs also resolved conflicts please review it
> 
> While checking your PR I was Not able to reset my password, can you tell me how this works ?

yes @swapnilsparsh  I have given a demo of how it works , kindly please check it 

1) Make sure you are updating the mail-id and password of the email from which you want to send email to the user
  https://user-images.githubusercontent.com/53329034/112500057-0dc87900-8dae-11eb-9ec3-dc60038a5a48.png

2) I'm attaching the video here kindly please review it


https://user-images.githubusercontent.com/53329034/113277699-a1460080-92fe-11eb-98e5-1201cdc61a17.mp4

**Pull request merged**
