### PR TITLE
Added option to call by clicking on phone icon in helpline_numbers.html

### PR DESCRIPTION
**Pull request by kanishka8276**
## Related Issue or bug
  - Info about Issue or bug
  - #125 

Fixes: #[issue number that will be closed through this PR]
#125
#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!
I have added phone icons next to each number and linked them to the number so that one they are clicked the associated number will be called.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
I ran it in my localhost
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.
NA
## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots
Screenshot (75)

### CODE REVIEW

**Comment by sakshikhachane** [comment]
@kanishka8276, `calloption` branch is not even with the `master` branch. because of this, I am unable to see the updated changes. If you are facing any problem doing this feel free to ping me on discord. Username - SAKSHI#0042

**Comment by kanishka8276** [comment]
@sakshikhachane done!

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Everthing is fine just one change and then it will be ready to merge.
One phone number should be in one line if there are multiple numbers then one number in one line.

**Comment by kanishka8276** [comment]
Ok !

**Comment by kanishka8276** [comment]
Screenshot (86)

**Pull request merged**
