### PR TITLE
Activist gallery style updated

### PR DESCRIPTION
**Pull request by tanishq-arya**
## Related Issue or bug
  - Styled the activist gallery page.

Fixes: #325 

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [x ] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |
 
 
Screenshot (1706)
Screenshot (1707)
Screenshot (1705)
Screenshot (1704)

### CODE REVIEW

**Comment by tanishq-arya** [comment]
For the text I have added scroll on hover. This looks much better than when I tried with points/lists. 
image

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Some images are stretching, fix it.

**Comment by tanishq-arya** [comment]
> Some images are stretching, fix it.

I'll try but they are stretching because the images are of different dimensions.

**Comment by tanishq-arya** [comment]
image
@swapnilsparsh Done. The images look much better and clear now.

**Comment by tanishq-arya** [comment]
Also I was thinking should I try to modify the cols, make them 2 cols in medium instead of three and make a single row with col wrap.

**Comment by tanishq-arya** [comment]
image
image
image

**Comment by tanishq-arya** [comment]
@swapnilsparsh I have not yet made a fresh pull for this branch as the manage.py file doesn't work. 
What should I do for the updated master ?
Should I pull from upstream and push to my master ?

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh I have not yet made a fresh pull for this branch as the manage.py file doesn't work. 
> What should I do for the updated master ?
> Should I pull from upstream and push to my master ?

Yes

**Comment by tanishq-arya** [comment]
> git pull --tags upstream master
From https://github.com/swapnilsparsh/Rescue
 * branch            master     -> FETCH_HEAD
error: unable to unlink old 'db.sqlite3': Invalid argument

getting this error

**Comment by tanishq-arya** [comment]
@swapnilsparsh I am getting this 
image

Should I just stage these changes and make push commit named merge ?

**Comment by tanishq-arya** [comment]
I tried with the master branch but it didn't push into this branch.

**Comment by tanishq-arya** [comment]
@swapnilsparsh I merged origin/master into this I think you can merge this now if everything is okay.

**Comment by swapnilsparsh** [comment]
@tanishq-arya Resolve the conflicts.

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Restyle the heading to the heading that is used in the website.

**Comment by tanishq-arya** [comment]
@swapnilsparsh this one ?
image

**Comment by tanishq-arya** [comment]
@swapnilsparsh I am unable to fetch any updates because of some database error. I had made a backup branch earlier so I'll make changes to that and raise a new PR.

**Pull request closed without merging**
