### PR TITLE
changed the carousel UI and made it Responsive which is in Home page

### PR DESCRIPTION
**Pull request by sourav-coder**
These are the samples pics of the new responsive carousel  :-

### CODE REVIEW

**Comment by swapnilsparsh** [comment]
Resolve the conflicts and then requeset a PR @sourav-coder

**Comment by sourav-coder** [comment]
@swapnilsparsh   Have a look I resolved the conflicts

**Comment by swapnilsparsh** [comment]
@sourav-coder  rescues.gif is showing two times, fix it and then make a PR
Annotation 2021-01-03 154530

**Comment by sourav-coder** [comment]
@swapnilsparsh  Please have a look now

**Pull request merged**
