### PR TITLE
Added Safety Manual

### PR DESCRIPTION
**Pull request by anushka1309paul**
The women's Safety manual has been added
It includes some general guidelines, tricks as well as self defence tips for women.

## Screenshots

image
image
image
image
image

### CODE REVIEW

**Comment by jatiinyadav** [comment]
Hey @anushka1309paul, resolve the conflicts.

**Comment by anushka1309paul** [comment]
Resolved the same.

**Comment by jatiinyadav** [comment]
Screenshot (37)
Screenshot (38)
Hey @anushka1309paul , Fix the issues mentioned below.
1. Use the same font as used in the website.
2. Instead of light blue color background use a different background so that the text is clearly visible.
3. Align the Heading (Attached Above).
4. The last photo you have used should be same as other pages (Attached Above).

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Change the bg colour so that the text can be readable
Resolve the conflicts.

**Comment by swapnilsparsh** [comment]
@anushka1309paul If possible close this PR and open a new PR linking your issue .

**Pull request closed without merging**
