### PR TITLE
Added google captcha 

### PR DESCRIPTION
**Pull request by 2001asjad**
Added the Google Captcha on both Register and the Login page as mentioned in the issue.

Fixes #241 

Attaching screenshots of both the pages below:
 The register page:
Register SS

The Login page:
Login SS

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Resolve the conflicts.

**Comment by sakshikhachane** [comment]
Hey @2001asjad,
Any updates?

**Comment by sakshikhachane** [comment]
@2001asjad Any updates?

**Comment by 2001asjad** [comment]
Well, I am not able to merge the conflicts @sakshikhachane

**Comment by sakshikhachane** [comment]
What problems are you facing?

**Comment by 2001asjad** [comment]
> What problems are you facing?

Hello @sakshikhachane , I just can't click the resolve button and address the changes.

**Comment by 2001asjad** [comment]
> @2001asjad Please refer to this - [https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github](url).
> Still if you are facing the problem then trying resolving conflicts on vs code else close this PR and make a new PR.

This PR has been open since a long time. The codebase might have changed a lot till now. So let me make a new one and I'm gonna update you soon.
Thanks btw @sakshikhachane

**Comment by sakshikhachane** [comment]
Okay then. I am closing this PR.

**Pull request closed without merging**
