### PR TITLE
Whatsapp messaging added

### PR DESCRIPTION
**Pull request by Tarun-Kamboj**
## Related Issue or bug
  Fixes: #154 

#### Describe the changes you've made

1. Users will now also be adding the the mobile numbers of their contacts.
2. Modified the views, form and model accordingly.
3. Added a script to send whatsapp messages.

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Tested by running the `EMERGENCY` functionality of the app.

#### Describe if there is any unusual behavior of your code
`NA`

## Checklist:
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.

## Screenshots
 Details available here https://github.com/swapnilsparsh/Rescue/issues/154#issuecomment-805518122

### CODE REVIEW

**Comment by sakshikhachane** [comment]
@Tarun-Kamboj The message won't be automatically sent right? We need to tap the button to send the message.

**Comment by Tarun-Kamboj** [comment]
> @Tarun-Kamboj The message won't be automatically sent right? We need to tap the button to send the message.

Messages are sent automatically. Is that not happening?

**Comment by sakshikhachane** [comment]
No @Tarun-Kamboj

**Comment by Tarun-Kamboj** [comment]
> No @Tarun-Kamboj
Can you try it again @sakshikhachane, it's working on my machine. 😅

**Comment by swapnilsparsh** [comment]
> > No @Tarun-Kamboj
> 
> Can you try it again @sakshikhachane, it's working on my machine. 😅

Not working 😕

**Comment by Tarun-Kamboj** [comment]
It waits for 20 secs to ensure stable internet connection and then sends the message.

**Comment by swapnilsparsh** [comment]
> Capture8
> 
> It waits for 20 secs to ensure stable internet connection and then sends the message.

Still not able to use this feature.

**Comment by Tarun-Kamboj** [comment]
@swapnilsparsh @sakshikhachane is it working now?

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh @sakshikhachane is it working now?

No

**Comment by Tarun-Kamboj** [comment]
I don't know how to fix this since it's working for me already.
If anyone know what's the problem and how to solve, please help.

**Comment by swapnilsparsh** [comment]
> I don't know how to fix this since it's working for me already.
> If anyone know what's the problem and how to solve, please help.

Can you share a working video ?

**Comment by Tarun-Kamboj** [comment]
> Can you share a working video ?

https://drive.google.com/file/d/1t8c7zAmLF5Ok1S2m5tunSFZAOiUWNVnr/view?usp=drivesdk
You can see here, I didn't touched the keyboard and the message got sent automatically.

**Comment by swapnilsparsh** [comment]
@Tarun-Kamboj Great Work.

**Comment by Tarun-Kamboj** [comment]
> @Tarun-Kamboj Great Work.

Thanks.

**Pull request merged**
