### PR TITLE
Contact page added #198

### PR DESCRIPTION
**Pull request by somya51p**
## Related Issue or bug
 This pull request is associated to issue number #198 

Fixes: #198
#### Describe the changes you've made
Added a complete contact page where users can send any message through e-mail and the admin would receive the message from the user.
( On running the following command, the message sent could be viewed:
python -m smtpd -n -c DebuggingServer localhost:587 )

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

 
 
 
 
 
 
 

@swapnilsparsh  @sakshikhachane Please review.

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Few changes:
1. Remove the pink box where address, phone and email are there.
2. Add some illustration.
3. Align all things center.

**Comment by somya51p** [comment]
@swapnilsparsh I have made the suggested changes. Please review the PR. Thank you!

**Comment by somya51p** [comment]
@swapnilsparsh Please review the PR.

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
I am unable to see the changes that you have made.

Fix the submit hover colour as button goes to white and font becomes pink when hoverning on the button

**Comment by somya51p** [comment]
@swapnilsparsh What type of hover should I apply then?

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh What type of hover should I apply then?

On hover green colour should be there as it is there on login page.

**Comment by sakshikhachane** [comment]
Hey @somya51p,
Any updates on the PR?

**Comment by swapnilsparsh** [comment]
@somya51p Resolve the conflicts

**Comment by sakshikhachane** [comment]
Hey @somya51p,
Can you please give us updates? We can't keep PR pending for more than 15 days unless we receive the updates or changes are being done.

**Comment by somya51p** [comment]
@sakshikhachane @swapnilsparsh I will be resolving the conflicts in the next two days. I was having quizzes in colledge due to which I was unable to give my contribution in a particular span.

**Comment by somya51p** [comment]
@sakshikhachane Changed the hover to green and resolved conflicts. Kindly review

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Resolve the conflicts

**Comment by somya51p** [comment]
@swapnilsparsh Resolved. Have a look

**Comment by sakshikhachane** [comment]
Hey @somya51p,
Sorry for the delayed response. We were trying to review this PR for a long time. But we are getting errors while fetching the PR. Can you please look into this?

**Comment by somya51p** [comment]
@sakshikhachane You need to run this command in a parallel terminal as I have given an smtpd response to it.
_python -m smtpd -n -c DebuggingServer localhost:587_ 
I have initially attached the screenshots it will work in the same manner.

**Comment by sakshikhachane** [comment]
@swapnilsparsh Can you have a look into this?

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Resolve the conflicts.

**Comment by somya51p** [comment]
@swapnilsparsh Done

**Pull request merged**
