### PR TITLE
added a user manual at home page

### PR DESCRIPTION
**Pull request by coding-geek21**
## Related Issue or bug
  - Info about Issue or bug

Fixes: #227 

#### Describe the changes you've made

Added a user manual section in home page with parallax effect on scrolling to make it attractive

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |
 
 
 
 
 
 

https://user-images.githubusercontent.com/53329034/114432134-fb3ba580-9bdd-11eb-909f-b9cfcdd4231b.mp4

### CODE REVIEW

**Comment by jatiinyadav** [comment]
Hey @coding-geek21, 
Just a suggestion, use the name of the issue you solved as your branch name instead of branch1, branch2

**Comment by coding-geek21** [comment]
> Hey @coding-geek21, 
> Just a suggestion, use the name of the issue you solved as your branch name instead of branch1, branch2 

Yes sure ! I will follow this next time thanks for your suggestion :)

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Great work !
Change the colour of the FAQ link text from blue to something else as it is not clear due to dark pink bg else everything is fine.

**Comment by coding-geek21** [comment]
> Great work !
> Change the colour of the FAQ link text from blue to something else as it is not clear due to dark pink bg else everything is fine.

Thank you! changed the link colour 
image

**Pull request merged**
