### PR TITLE
Safety Manual Added

### PR DESCRIPTION
**Pull request by anushka1309paul**
Fixes: #230

Description:
Added Women's Safety tips with all required changes.

Checklist:
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by anushka1309paul** [comment]
Kindly merge this pull request now.

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
ss
Resolve this error.

**Comment by anushka1309paul** [comment]
How do I fix it?

**Comment by swapnilsparsh** [comment]
> How do I fix it?

You might have made changes somewhere else that leads to this error.

**Pull request closed without merging**
