### PR TITLE
preloader-added

### PR DESCRIPTION
**Pull request by Ankita297**
## Related Issuse or bug
  - addition of website preloader
Fixes: #104 

#### Describe the changes you've made
I have added a preloader in the website which will display for 2 second because the website loads very fast so i added settime out  function to display it for atleast 2 second .

## Type of change

Please delete options that are not relevant.

- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [x ] Code style update (formatting, local variables)
- [x ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x ] This change requires a documentation update

## How Has This Been Tested?

I have tested it in my local system.
#### NA
A clear and concise description of it.

## Checklist:

- [x ] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [x ] I have made corresponding changes to the documentation.
- [x ] My changes generate no new warnings.
- [x ] I have added tests that prove my fix is effective or that my feature works.
- [x ] New and existing unit tests pass locally with my changes.
- [x ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |

 https://user-images.githubusercontent.com/67833077/110609680-78c15f80-81b3-11eb-9843-7b4c61251b3c.mp4

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Preloader which you have made is very good.
You have to make few changes:
1. The photo is preloader which you have used is stretcing so avoid stretching of the photo.
2. Use some circular lines around the photo or something else.

**Comment by Ankita297** [comment]
Okay Sir . I will make the changes .

**Comment by Ankita297** [comment]
127 0 0 1_8000 - Google Chrome 11-03-2021 20_22_18

**Comment by Ankita297** [comment]
Something like this ?
127 0 0 1_8000 - Google Chrome 11-03-2021 20_22_18

**Comment by Ankita297** [comment]
https://user-images.githubusercontent.com/67833077/110806781-67a64a80-82a8-11eb-9456-94983ea8726d.mp4

**Comment by Ankita297** [comment]
Is it okay ?

**Comment by Ankita297** [comment]
or Should i  remove the image

**Comment by swapnilsparsh** [comment]
> or Should i remove the image

Image is appearing stretched and it is also getting croped automatically by the circle so you can try some different shape or different preloader and add something in background as it looks plain.

**Comment by Ankita297** [comment]
https://user-images.githubusercontent.com/67833077/110919792-a557b180-8342-11eb-99d0-f3317b860115.mp4

**Comment by swapnilsparsh** [comment]
>  New.Tab.-.Google.Chrome.2021-03-12.11-07-55.mp4

Preloader is not good enough as compared to last one.
Use the last preloader that you have made and there only make changes that I have asked you to do.

**Comment by Ankita297** [comment]
https://user-images.githubusercontent.com/67833077/111032159-e1694000-8430-11eb-955a-0a5827655011.mp4

**Comment by Ankita297** [comment]
Sir is it okay ?You can tell me then i will make the changes . 
The photo will be stretched because it is gif .

**Comment by Ankita297** [comment]
If you require any color changes then tell me ?

**Comment by swapnilsparsh** [comment]
> If you require any color changes then tell me ?

If you will increase the size of the circle or if you will edit the gif before hand before using in the preloader then gif will not stretched.
Use some dark solid colour in background.

**Comment by Ankita297** [comment]
https://user-images.githubusercontent.com/67833077/111059010-60558b80-84b8-11eb-8d54-ae5e2852ec0e.mp4

**Comment by Ankita297** [comment]
Sir i have converted the gif into jpg so it is not stretching now .
But if i make the circle large it will not suit .

**Comment by Ankita297** [comment]
Document - Google Chrome 14-03-2021 11_47_26

**Comment by Ankita297** [comment]
I have not made  the commit yet . If it is okay then i will make the commit .

**Comment by swapnilsparsh** [comment]
> Sir i have converted the gif into jpg so it is not stretching now .
> But if i make the circle large it will not suit .

img {
    height: 300px
    width: 100%;
    object-fit: cover;
}

Use this, then the image will not stretch.

You can keep bg plain aur keep relevant to Rescue theme.

**Comment by swapnilsparsh** [comment]
> Sir i have converted the gif into jpg so it is not stretching now .
> But if i make the circle large it will not suit .

img {
height: 300px
width: 100%;
object-fit: cover;
}

Use this, then the image will not stretch.

You can keep bg plain aur keep relevant to Rescue theme.

**Comment by Ankita297** [comment]
https://user-images.githubusercontent.com/67833077/111202154-9181a900-85e9-11eb-9fa1-a007ea68df8d.mp4

**Comment by Ankita297** [comment]
is it okay now ?

**Comment by Ankita297** [comment]
if it is okay then i will make the commit .

**Comment by swapnilsparsh** [comment]
Yes, its okay now

**Comment by Ankita297** [comment]
Done Sir.

**Comment by sakshikhachane** [comment]
Hey @Ankita297,
Please resolve the conflicts and then PR is ready to be merged then :)

**Comment by Ankita297** [comment]
Done Mam.

**Comment by sakshikhachane** [comment]
@Ankita297 Few changes - 
- [ ] Below navbar, one blue line is coming up. Please remove it.
- [ ] The gif image is repeated twice on the `home page`. Fix it.
- [ ] The styles are also visible on the website. Fix this.

**Comment by Ankita297** [comment]
https://user-images.githubusercontent.com/67833077/111325682-eb3dae00-8691-11eb-9511-32ad70e3bec4.mp4

**Comment by Ankita297** [comment]
Mam there are no such bugs from my site.

**Comment by sakshikhachane** [comment]
@Ankita297 Always keep your forked repo updated with the original repo. Not only forked repo but the branch you are working on also should be even with the `master` branch. Please do the same. If you require any help here, do tell me I will guide you :)

**Comment by Ankita297** [comment]
So mam what sholud i do now ?

**Comment by Ankita297** [comment]
Mam i have updated my master branch .  So what should i do to update my feature branch to current repo?

**Comment by Ankita297** [comment]
https://user-images.githubusercontent.com/67833077/111412783-17ddde00-8703-11eb-90f0-5f055871f91d.mp4

**Comment by Ankita297** [comment]
is it okay now ?
Should i make the commit .

**Pull request merged**
