### PR TITLE
Contact page enhanced

### PR DESCRIPTION
**Pull request by tanishq-arya**
## Related Issue or bug
  - modified layout,font,styles
Fixes: #362 

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [ x] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |
 
image
image
image

### CODE REVIEW

**Comment by tanishq-arya** [comment]
@swapnilsparsh should I also enhance create contact form in this issue? If yes can you make this level 3?
image

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
1. Completely remove the left-hand side section and add an illustration instead.
2. Add Github and Linkedin links of mine.

**Comment by tanishq-arya** [comment]
image
image

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
1. Use some other illustration as the illustration which you have used there is a blank screen on mobile.
2. Use the square icon with rounded corners for Github and Twitter (Linkedin already have that icon).
3.  Align the logos next to the Submit Button.

**Comment by tanishq-arya** [comment]
Where is the twitter link ? Can you please share it.

**Comment by tanishq-arya** [comment]
Is this one okay?
image

**Comment by tanishq-arya** [comment]
Or this one
image

**Comment by tanishq-arya** [comment]
https://user-images.githubusercontent.com/77333275/120313200-4b3e0b00-c2f7-11eb-9f95-e4982ac20286.mp4

I made the icons floating earlier so should I remove the animation and align them ?

**Comment by tanishq-arya** [comment]
@swapnilsparsh twitter link ?

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh twitter link ?

https://twitter.com/swapnilsparsh

**Pull request merged**
