### PR TITLE
Latest changes :

### PR DESCRIPTION
**Pull request by SUMEKAGARWAL**
Latest changes

### CODE REVIEW

**Comment by SUMEKAGARWAL** [comment]
@swapnilsparsh !
Here is the new PR with requested changes!
Please have a look into it!

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
bug
When hovering on emergency button , text is not clearly visible.

You forget to link the issue again.

**Comment by SUMEKAGARWAL** [comment]
@swapnilsparsh I didnt do anything to that emergency button.

**Comment by sakshikhachane** [comment]
@SUMEKAGARWAL Keep your master branch updated with the master branch of the forked repository. I think this will resolve the problem.

**Comment by swapnilsparsh** [comment]
> @SUMEKAGARWAL Keep your master branch updated with the master branch of the forked repository. I think this will resolve the problem.

@SUMEKAGARWAL Do this.

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh I didnt do anything to that emergency button.

You have to make few changes in css were hover is used in women safety laws and women rights page.

**Comment by sakshikhachane** [comment]
Hey @SUMEKAGARWAL,
Any updates?

**Comment by sakshikhachane** [comment]
> You have to make few changes in css were hover is used in women safety laws and women rights page.

Are you talking about this change?

**Comment by SUMEKAGARWAL** [comment]
@sakshikhachane yes!

**Comment by sakshikhachane** [comment]
Can you link the issue for which this PR is created in description?

**Comment by sakshikhachane** [comment]
@SUMEKAGARWAL We can't keep PR for such a long time. There are many participants who want to work. Please respond else we will have to close this PR.

**Comment by SUMEKAGARWAL** [comment]
Fixes: #178
Modified changes :

Hovering issue in womens_rights.html.
Committed "YES" or "NO" change in delete_contact.html
Elements in threads of "Emergency Contact " page are not accurately assigned...so did that!

sorry for the inconvenience!

**Review by sakshikhachane — CHANGES_REQUESTED** [review]
Hey @SUMEKAGARWAL,
- [ ] Hovering issue is not yet fixed. 
- [ ] Unable to open `emergency_contact` page.
- [ ] Remove the `0001_intitial.py` file.

If you feel you have done this then share the working demo because I am not able to see the changes.

**Comment by SUMEKAGARWAL** [comment]
image
image
There were some more changes that I did, but according to the saying, I reverted those to it.
At present only these two changes are what I made.

**Comment by SUMEKAGARWAL** [comment]
@sakshikhachane If you want me to work on some other thing, I am ready to do so.

**Comment by swapnilsparsh** [comment]
@SUMEKAGARWAL Did you resolved the issues that @sakshikhachane asked?

**Comment by SUMEKAGARWAL** [comment]
She asked me shoe the changes that I made.
And so I shared the screen shots.

**Comment by swapnilsparsh** [comment]
@SUMEKAGARWAL 

The hovering issue is not yet fixed.
Unable to open emergency_contact page.
Remove the 0001_intitial.py file.
Resolve the conflicts.

**Comment by khanfarhan10** [comment]
Resolve all conflicts @SUMEKAGARWAL

**Comment by SUMEKAGARWAL** [comment]
@swapnilsparsh Why was my PR isn't merged?

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh Why was my PR isn't merged?

There were some errors while running your code and the last date to merge the PR was 5th June.

**Pull request closed without merging**
