### PR TITLE
Footer

### PR DESCRIPTION
**Pull request by nehaparmar99**
## Related Issuse or bug
  - FIx the footer

Fixes: #76

#### Describe the changes you've made
The margin of the footer has been set in the common template, and for the home flexbox has been added

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots
ORIGINAL 
105365964-d231f700-5c24-11eb-9829-655e510518e9
105365972-d3632400-5c24-11eb-8516-f18f75f380fe

UPDATED
All the pages now have a footer attached to the bottom
ss
The homepage now has a responsive footer
Screenshot (279)

### CODE REVIEW

**Comment by swapnilsparsh** [comment]
Everything is fine just one change is required that make the homepage footer as you have made the other pages footer.
Don't collapse the text when checking it is responsive or not. on homepage footer

**Comment by nehaparmar99** [comment]
> Everything is fine just one change is required that make the homepage footer as you have made the other pages footer.
> Don't collapse the text when checking it is responsive or not on homepage footer

Should I decrease the font size then?Or make the 2 of them display as columns?

**Comment by swapnilsparsh** [comment]
footer

Provide some space between footer and page.

**Comment by nehaparmar99** [comment]
> footer
> 
> Provide some space between footer and page.
 Resolved it now!

**Comment by nehaparmar99** [comment]
@swapnilsparsh For a footer similar to others, the page layout will have to be changed this way, is it fine?
It's happening because of the jquery import which wasnt done earlier
Screenshot (281)

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh For a footer similar to others, the page layout will have to be changed this way, is it fine?
> It's happening because of the jquery import which wasnt done earlier.Should i push the code for it?
> Screenshot (281)
> 
It's looking fine.

**Comment by swapnilsparsh** [comment]
@nehaparmar99 Just fix the homepage footer.

**Comment by nehaparmar99** [comment]
I've pushed the code. Let me know if any other changes are required

**Comment by nehaparmar99** [comment]
> > @swapnilsparsh For a footer similar to others, the page layout will have to be changed this way, is it fine?
> > It's happening because of the jquery import which wasnt done earlier.Should i push the code for it?
> > Screenshot (281)
> 
> It's looking fine.

I've pushed the code for this.Let me know if any other changes are required.

**Comment by swapnilsparsh** [comment]
@nehaparmar99 Resolve the conflicts

**Comment by nehaparmar99** [comment]
> @nehaparmar99 Resolve the conflicts

Done!

**Pull request merged**
