### PR TITLE
QA : Format & Lint

### PR DESCRIPTION
**Pull request by Aryamanz29**
Fixes: #304

## Describe the changes you've made

- Integrate [Black](https://pypi.org/project/black/) and [Flake8](https://pypi.org/project/flake8/) for format & linting of source code
- Added workflow `.github/workflows/qa_checks.yml` and script `rescue_QA_checks` , Which ensures contributor follow [PEP8](https://www.python.org/dev/peps/pep-0008/) standard for python.
- Update `README.md` with `how to run` instructions.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

- Tested on Github actions, See build below👇
**Success Build:** https://github.com/Aryamanz29/Rescue/actions/runs/852479277

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by swapnilsparsh** [comment]
@Aryamanz29 Resolve the conflicts.

**Comment by Aryamanz29** [comment]
@swapnilsparsh Resolved Conflicts. Please Review It again.
**Success Build**: https://github.com/Aryamanz29/Rescue/actions/runs/866354520

**Comment by swapnilsparsh** [comment]
@Aryamanz29 Resolve the conflicts.

**Comment by Aryamanz29** [comment]
> @Aryamanz29 Resolve the conflicts.

    I have got conflicts because project admin merge other PR before mine .. then I have to update again.. please review early otherwise this will happen again .. I'll update again ✌️

**Comment by Aryamanz29** [comment]
@swapnilsparsh  **Success Build** : https://github.com/Aryamanz29/Rescue/actions/runs/871025630

**Pull request merged**
