### PR TITLE
added account activation functionality by sending activation link to user via email - issue #190

### PR DESCRIPTION
**Pull request by coding-geek21**
## Related Issue or bug
  - Added account activation functionality by sending activation link via mail after the user registers using email id

Fixes: #190 

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |
 
###  After user registers using mail id :

image

### When user tries to login before account activation :

image

### Email with activation link :

image

### After activating account using the link from the email :

image

### After successful login :

image

 

**Please do update the settings.py with respective email id and password to test this functionality**
image

### CODE REVIEW

**Comment by coding-geek21** [comment]
@sakshikhachane  @swapnilsparsh  please review my PR :)

**Comment by swapnilsparsh** [comment]
> @sakshikhachane @swapnilsparsh please review my PR :)

Can you tell if user gives only username at registration then how come conifmation mail will be sent?

**Comment by coding-geek21** [comment]
> > @sakshikhachane @swapnilsparsh please review my PR :)
> 
> Can you tell if user gives only username at registration then how come conifmation mail will be sent?

No already I worked on the issue where the user registers their email during registration itself

**Comment by coding-geek21** [comment]
> > > @sakshikhachane @swapnilsparsh please review my PR :)
> > 
> > Can you tell if user gives only username at registration then how come conifmation mail will be sent?
> 
> No already I worked on the issue where the user registers their email during registration itself



Registeration using email is mandatory

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
While checking your PR I am not getting any mail regarding activation.
Kindly fix it.

**Comment by coding-geek21** [comment]
> While checking your PR I am not getting any mail regarding activation.
> Kindly fix it.

@swapnilsparsh  pls do install  six-> (pip install six) as we are using it for generating a unique links

**Comment by coding-geek21** [comment]
> > While checking your PR I am not getting any mail regarding activation.
> > Kindly fix it.
> 
> @swapnilsparsh pls do install six-> (pip install six) as we are using it for generating a unique links
Also please do check in the spam folder too

**Comment by coding-geek21** [comment]
https://user-images.githubusercontent.com/53329034/112779494-7b053400-9064-11eb-829a-910f470f8643.mp4

@swapnilsparsh  I have attached the working of the code here kindly check it 
1.kindly make sure that you are updating email and password of the email in settings.py page
2. Do `pip install six` as it is needed for generating a link
3.  Also kindly please check the spam folder for the email

**Comment by swapnilsparsh** [comment]
> > While checking your PR I am not getting any mail regarding activation.
> > Kindly fix it.
> 
> @swapnilsparsh pls do install six-> (pip install six) as we are using it for generating a unique links

Please mention it before hand that we have to install something else it will not work.
Give me some time to review your PR as it is a backend issue so I will check it thoroughly then only I can tell you anything else regarding this PR until then please wait.

**Comment by coding-geek21** [comment]
> > > While checking your PR I am not getting any mail regarding activation.
> > > Kindly fix it.
> > 
> > @swapnilsparsh pls do install six-> (pip install six) as we are using it for generating a unique links
> 
> Please mention it before hand that we have to install something else it will not work.
> Give me some time to review your PR as it is a backend issue so I will check it thoroughly then only I can tell you anything else regarding this PR until then please wait. 

Ok @swapnilsparsh

**Pull request merged**
