### PR TITLE
Added location update feature

### PR DESCRIPTION
**Pull request by jainayush362**
## Related Issue or Feature
  - Added Location Update feature.

Fixes: #158 

#### Describe the changes you've made
1. On the login dashboard where Emergency contacts are stored, a button "Send Continuous Location for 30 mins" has been added. On clicking this button for 30 mins duration a location alert will be sent on email at every 10 mins interval with updated Location link. The user can click the link again after 30 mins.

2. In "mail.py" instead of entering Email again and again a global variable Email and Password has been added which stores the respective values.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Used VPN to test whether the location is updating or not. It is working

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.

## Screenshots

image

image

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Everything is working fine but after the mail is sent then also it keeps on loading the screen and there is no confirmation page that the mail has been sent is shown.

**Comment by jainayush362** [comment]
> Everything is working fine but after the mail is sent then also it keeps on loading the screen and there is no confirmation page that the mail has been sent is shown.

Ok.....I will do the required changes

**Comment by sakshikhachane** [comment]
@jainayush362 Any updates?

**Comment by jainayush362** [comment]
> @jainayush362 Any updates?

Hey @sakshikhachane I have tried doing changes but the page still keeps on loading till the process of sending updates get completed.

**Comment by sakshikhachane** [comment]
> Hey @sakshikhachane I have tried doing changes but the page still keeps on loading till the process of sending updates get completed.

@swapnilsparsh Can you look over this?

**Comment by swapnilsparsh** [comment]
> > @jainayush362 Any updates?
> 
> Hey @sakshikhachane I have tried doing changes but the page still keeps on loading till the process of sending updates get completed.

Do you want more time or you want someone else to resolve this issue ?

**Comment by jainayush362** [comment]
> > > @jainayush362 Any updates?
> > 
> > 
> > Hey @sakshikhachane I have tried doing changes but the page still keeps on loading till the process of sending updates get completed.
> 
> Do you want more time or you want someone else to resolve this issue ?

Hi @swapnilsparsh I tried my best on this. I think someone new should be assigned to resolve this issue.

**Pull request closed without merging**
