### PR TITLE
Created Register page using email id for user registration , issue #183

### PR DESCRIPTION
**Pull request by coding-geek21**
## Related Issue or bug
  -  Created the register page using email id for User registration and added relevant validation if the email-id already exists

Fixes: #183 

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b>|

image

### CODE REVIEW

**Comment by sakshikhachane** [comment]
@coding-geek21 Great work!
Just one suggestion. Never make any changes to the `master` branch and it must be even with the remote `master` branch.

**Comment by sakshikhachane** [comment]
@coding-geek21 The issue mentioned creating `Sign in` as well. Please make the changes in the `login` page as well.

**Comment by coding-geek21** [comment]
> @coding-geek21 The issue mentioned creating `Sign in` as well. Please make the changes in the `login` page as well.

Yeah @sakshikhachane I have doubt regarding that should I add email id as additional or should I remove username and add email instead of it

**Comment by coding-geek21** [comment]
> @coding-geek21 Great work!
> Just one suggestion. Never make any changes to the `master` branch and it must be even with the remote `master` branch.

Thanks a lot @sakshikhachane ! I will follow up your suggestion from next time onwards 😊

**Comment by sakshikhachane** [comment]
> > @coding-geek21 The issue mentioned creating `Sign in` as well. Please make the changes in the `login` page as well.
> 
> Yeah @sakshikhachane I have doubt regarding that should I add email id as additional or should I remove username and add email instead of it

@coding-geek21 I will confirm this from the PA of this project and let you know. 
But can we do it like this - keep `Username\Email` and one can log in using both username and email as per one's choice?

**Comment by coding-geek21** [comment]
> > > @coding-geek21 The issue mentioned creating `Sign in` as well. Please make the changes in the `login` page as well.
> > 
> > Yeah @sakshikhachane I have doubt regarding that should I add email id as additional or should I remove username and add email instead of it
> 
> @coding-geek21 I will confirm this from the PA of this project and let you know. 
> But can we do it like this - keep `Username\Email` and one can log in using both username and email as per one's choice?

Yeah that's good idea

**Comment by sakshikhachane** [comment]
> Yeah that's good idea

Please do it then:)

**Comment by coding-geek21** [comment]
> > Yeah that's good idea
> 
> Please do it then:)

**Comment by coding-geek21** [comment]
> > > Yeah that's good idea
> > 
> > 
> > Please do it then:)

Hi @sakshikhachane  I have made login using both email and username please review it :)

**Comment by sakshikhachane** [comment]
Good work!

**Comment by coding-geek21** [comment]
> Good work!

Thank you ! @sakshikhachane

**Pull request merged**
