### PR TITLE
Login page similar to register page

### PR DESCRIPTION
**Pull request by mansijain980**
Fixes: #160 

#### Description
Made login page as register page with required changes.

## Checklist:
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Review by sakshikhachane — CHANGES_REQUESTED** [review]
- [ ] Remove `db.sqlite3` , `mail.py` and `settings.py` files from PR.
- [ ] `create_contact.html` page is not related to this issue. Remove this file as well.
- [ ] For the text `Login through Registered Account`, make it `Login` only.
- [ ] `Username or Email:` and `Password` fields should be beside the image at the center.
- [ ] Show the working of `login` page, first by registering and then log in - through video.

**Comment by mansijain980** [comment]
image
when i m registering through google it occurs but when i register by email then it shows this (screenshotted above).
Let me know why ?

**Comment by sakshikhachane** [comment]
@mansijain980 That is a bug. I have created an issue for this. Complete the changes as you have to do changes only on the front end part.
Also remove the `db.sqlite3` file.

**Comment by mansijain980** [comment]
Done mam.

**Comment by mansijain980** [comment]
image
db.sqlite3 file is not there in my PR.

**Comment by sakshikhachane** [comment]
> image
> db.sqlite3 file is not there in my PR.

The image itself depicts the file.
Resolve the conflicts.

**Comment by swapnilsparsh** [comment]
@mansijain980 Resolve the conflicts

**Comment by swapnilsparsh** [comment]
@mansijain980 Conflicts are not resolved yet.

**Comment by mansijain980** [comment]
@swapnilsparsh sir , i am thinking to delete this branch to  close this PR and will commit a new PR . Because of conflicts , it created mess.
can i?

**Comment by mansijain980** [comment]
image
There r no conflicts in thhis branch.

**Comment by mansijain980** [comment]
> @swapnilsparsh sir , i am thinking to delete this branch to close this PR and will commit a new PR . Because of conflicts , it created mess.
> can i?

?

**Comment by swapnilsparsh** [comment]
> > @swapnilsparsh sir , i am thinking to delete this branch to close this PR and will commit a new PR . Because of conflicts , it created mess.
> > can i?
> 
> ?

Sure

**Pull request closed without merging**
