### PR TITLE
Added profile section with update option

### PR DESCRIPTION
**Pull request by vidhishah03**
-  Changed register view for user 
-  Added a user profile which doesn't allow to change the username but allows to change fields like profile picture, email id, phone number and about me.

image

### CODE REVIEW

**Comment by sakshikhachane** [comment]
@swapnilsparsh Please review this PR.

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
I am facing errors while running your code, fix it.

**Comment by vidhishah03** [comment]
Can you please tell me what errors are you facing? I will check from my side too as it is working well on my system

**Comment by swapnilsparsh** [comment]
> Can you please tell me what errors are you facing? I will check from my side too as it is working well on my system

While running the code it's showing error.

**Comment by sakshikhachane** [comment]
@vidhishah03 Any updates?

**Comment by vidhishah03** [comment]
@sakshikhachane Can you please assign this to someone else and I am unable to resolve errors from my side? I will contribute to another issues.

**Pull request closed without merging**
