### PR TITLE
added confirmation mail sent page

### PR DESCRIPTION
**Pull request by coding-geek21**
## Related Issue or bug
  -added confirmation mail sent page

Fixes: #324 ]

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |
 
 
image

### CODE REVIEW

**Comment by swapnilsparsh** [comment]
@coding-geek21 When clicking on the activation link through Gmail does it redirect to the login page or we have to manually go to the login page to get into the account?

**Comment by coding-geek21** [comment]
> @coding-geek21 When clicking on the activation link through Gmail does it redirect to the login page or we have to manually go to the login page to get into the account?

it automatically redirects to the login page

**Comment by coding-geek21** [comment]
> @coding-geek21 When clicking on the activation link through Gmail does it redirect to the login page or we have to manually go to the login page to get into the account?

It automatically redirect to the login page @swapnilsparsh

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Add an option if the user wants to redirect to Gmail then it can happen through the same page.

**Comment by coding-geek21** [comment]
> Add an option if the user wants to redirect to Gmail then it can happen through the same page.

image

Made changes @swapnilsparsh

**Pull request merged**
