### PR TITLE
Enhanced Create Contacts Page

### PR DESCRIPTION
**Pull request by mansijain980**
Fixes: #157 

#### Describe the changes you've made
Enhanced the page with css and bootstrap.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)

## Checklist:
- [] My code follows the code style of this project.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |
 
image

### CODE REVIEW

**Comment by mansijain980** [comment]
Please Check it .
Thanks

**Review by sakshikhachane — CHANGES_REQUESTED** [review]
- [ ] Remove `db.sqlite3` file
- [ ] The text `Create contacts of your trustworthy people who can help you when you need their help in any emergency.` and `They will get notify when you are in danger!!` should be aligned in the center.
- [ ] Leave some space before and after the `CREATE` button.
- [ ] For smaller screen devices, bring the form to the center of the page.

**Review by sakshikhachane — CHANGES_REQUESTED** [review]
- [ ] Remove the `db.sqilte3` file.
- [ ] For the screen width below `995px`. Make the width of the form to 75% and make the font size such that the text is readable.

**Review by sakshikhachane — CHANGES_REQUESTED** [review]
- [ ]Please remove the `db.sqilte3` file. This is the 3rd time I am asking you.

**Comment by swapnilsparsh** [comment]
@mansijain980 Resolve the conflicts.

**Comment by swapnilsparsh** [comment]
@mansijain980 Resolve the conflicts.

**Comment by swapnilsparsh** [comment]
@mansijain980 There are some bugs and errors, please rebase the code to master and commit again.

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
There are some bugs, please rebase the code and commit again.

**Comment by mansijain980** [comment]
Sorry sir , but please have a look .
image
There r no conflicts from my side .

**Comment by swapnilsparsh** [comment]
@mansijain980 Resolve the conflicts.

**Comment by mansijain980** [comment]
> @mansijain980 Resolve the conflicts.

Done sir.

**Comment by swapnilsparsh** [comment]
@mansijain980 Resolve the conflicts.

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Rebase your code as I am unable to login into the site and see your contact page.

**Comment by swapnilsparsh** [comment]
@mansijain980 You have opened two PR regarding this issue, kindly close one issue in order to get your PR merged.

**Comment by mansijain980** [comment]
@swapnilsparsh please close this PR . I have requested a new pr.

**Pull request closed without merging**
