### PR TITLE
added illustrations in password reset pages and enhanced using css

### PR DESCRIPTION
**Pull request by coding-geek21**
Enhanced the all the password reset pages using css 
  -Added illustrations in  
1. password_reset
2. password_reset_form
3. password_reset_sent
4. password_reset_done

Fixes: #311 

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |
 
 
https://user-images.githubusercontent.com/53329034/118823925-0669ab80-b8d7-11eb-8bb1-568b8cbbb20f.mp4

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Instead of manually changing the domain, Can you do it automatically?

**Comment by coding-geek21** [comment]
> Instead of manually changing the domain, Can you do it automatically?

Actually @swapnilsparsh  this occurs because in django admin the sites table has domain name as  example.com as an entry so in mail the same link is being sent for password reset , I changed this in previous issue for Changing password where i made changes to db.sqlite3 file so now as it was merged, now no changes has to be done for domain name . I have also attached the demo.


https://user-images.githubusercontent.com/53329034/119214200-9e87b080-bae2-11eb-8060-73fb8993e07e.mp4

**Comment by swapnilsparsh** [comment]
@coding-geek21 Resolve the conflicts.

**Comment by coding-geek21** [comment]
> @coding-geek21 Resolve the conflicts.

@swapnilsparsh Done

**Pull request merged**
