### PR TITLE
updated women safety laws page

### PR DESCRIPTION
**Pull request by Sloth-Panda**
corresponds to issue-> #4

### CODE REVIEW

**Comment by swapnilsparsh** [comment]
@Sloth-Panda 
Refer to #11

**Comment by Sloth-Panda** [comment]
@swapnilsparsh  can you please check this pr has resolved the conflicts and also checked out the issue you have refered to #11 and I guess I have made improvement on it . Let me know if any further improvements on it is required

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh can you please check this pr has resolved the conflicts and also checked out the issue you have refered to #11 and I guess I have made improvement on it . Let me know if any further improvements on it is required

You are making changes in html file that you don't have to do.
Kindle refer to #11 and get an idea how you have to resolve this issue.

**Comment by Sloth-Panda** [comment]
@swapnilsparsh I have already checked the issue that you are refering to many times and it basically contains 20-30 commits of how your women safety laws page was made , can you please give a better clarity of what you want from this issue ?

**Pull request closed without merging**
