### PR TITLE
changes full navbar code

### PR DESCRIPTION
**Pull request by Muskan-creator**
## change navbar full code into readable file ,remove bugs,add css
  - Info about Issue or bug

Fixes: #217

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
1. Align the navbar to the right side.
Navbar align
<hr>

2. Change the navbar colour to the previous colour.
navbar colour
<hr>

3.  Fix the navbar transparency bug and change the navbar colour.
navbar transparency

**Comment by Muskan-creator** [comment]
Ok I will work on this I changed UI color because it matches with theme.

**Comment by Muskan-creator** [comment]
image
Made requested changes please review @swapnilsparsh

**Comment by Muskan-creator** [comment]
image

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
navbar

Add this feature to common.html also.

**Comment by Muskan-creator** [comment]
I have added hover effect to common.html
image

**Comment by Muskan-creator** [comment]
Please merge my pr @swapnilsparsh

**Comment by swapnilsparsh** [comment]
> I have added hover effect to common.html
> image

I am unable to see the hover effect that you have added to common.html.
There might be some issue, resolve it.

**Comment by Muskan-creator** [comment]
image
I have checked it is running in my local pc

**Comment by swapnilsparsh** [comment]
> image
> I have checked it is running in my local pc

Push the code again, there might be some bug.

**Comment by swapnilsparsh** [comment]
@Muskan-creator Resolve the conflicts

**Comment by Muskan-creator** [comment]
Please check now @swapnilsparsh

**Pull request merged**
