### PR TITLE
created change password page

### PR DESCRIPTION
**Pull request by coding-geek21**
## Related Issue or bug
  - Created change password functionality

Fixes: #197 

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |
 
 
 
 
 
 
 
 
 

https://user-images.githubusercontent.com/53329034/117149557-f335e680-add4-11eb-8e44-39ca76e86532.mp4

### CODE REVIEW

**Comment by coding-geek21** [comment]
@sakshikhachane actually there is some issues after making PR and when I clone and run in my local Pc it's showing some error but before making the PR everything is working fine , I'm trying hard to resolve it, if you have any idea why this happens please suggest me, I guess there is some issues in some pull request that is merged before , May be that's causing  conflicts for the new PR, I also found the same issue with some other person who is working on update profile

**Comment by coding-geek21** [comment]
@sakshikhachane  Can i fork this repo again? and work on it?

**Comment by coding-geek21** [comment]
@sakshikhachane there is some issues with unique email check and username check which is conflicting with register page
when i checked after removing the code for unique email check and username check I can see that the register functionality is working perfectly fine please ask the contributor of #226  to check this , this is why register functionality is not working

**Comment by coding-geek21** [comment]
@sakshikhachane  i found that the Google auth has expired in my local files
image


that's why there is no google auth in my recent PR

I will update you after making changes

**Comment by sakshikhachane** [comment]
@swapnilsparsh Can you have a look at this?

**Comment by swapnilsparsh** [comment]
> @sakshikhachane i found that the Google auth has expired
> image
> This is why it's showing error and login using google is not working , so what should i do now?
> 
> Pls update me

Update the API and then check wether it is working or not.

**Comment by coding-geek21** [comment]
> @coding-geek21 Is it working now?

I will update regarding this by today i'm working on it

**Comment by coding-geek21** [comment]
And yes this functionality is not working when there is no entry in social applications in Admin page and it works fine if the google api is added 

https://user-images.githubusercontent.com/53329034/117848566-0cd9a100-b2a1-11eb-927f-2ed1dc4a929c.mp4

**Comment by coding-geek21** [comment]
When i cloned and tried running the code it works fine so I guess there is no issues now

**Comment by swapnilsparsh** [comment]
@coding-geek21 Push the new commits.

**Comment by coding-geek21** [comment]
> @coding-geek21 Push the new commits.

@swapnilsparsh Done, Please check whether it's working now

**Comment by coding-geek21** [comment]
@swapnilsparsh  I have added the db.sqlite3 file can you check now with google api , It's working now , can you check and tell me

**Comment by coding-geek21** [comment]
Please view this demo

https://user-images.githubusercontent.com/53329034/118387875-7b6e8400-b63e-11eb-87a4-5b8eed9f1f32.mp4

And I have one suggestion can you change it to level 3 as i have also worked on backend

**Comment by swapnilsparsh** [comment]
@coding-geek21 Resolve the conflicts.

**Comment by coding-geek21** [comment]
> @coding-geek21 Resolve the conflicts.

@swapnilsparsh Done

**Pull request merged**
