### PR TITLE
Fixed Font sizes for mobile view

### PR DESCRIPTION
**Pull request by tanishq-arya**
## Related Issue or bug
  - Fixed font sizes on mobile view.

Fixes: #186 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [x ] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |
:---------------------------:|: 
image
image
image
image
image
image

 :|

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Resolve the conflicts.

**Comment by swapnilsparsh** [comment]
@tanishq-arya Give me some time to review your code.

**Comment by swapnilsparsh** [comment]
@tanishq-arya Everything is working fine just fix the new pages that were added and then it will be fine.

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
There are no photos on the website, fix this bug.

**Comment by tanishq-arya** [comment]
> There are no photos on the website, fix this bug.

@swapnilsparsh where ? I can see the pictures on my side. 
image

**Comment by swapnilsparsh** [comment]
@tanishq-arya Reabse the code and commit it again, might be there is some bug.

**Comment by tanishq-arya** [comment]
> git pull --tags -r
Your configuration specifies to merge with the ref 'refs/heads/font-sizes'
from the remote, but no such ref was fetched.

**Comment by swapnilsparsh** [comment]
> > git pull --tags -r
> > Your configuration specifies to merge with the ref 'refs/heads/font-sizes'
> > from the remote, but no such ref was fetched.

1. Align the More Details Button in Women's Rights.
2. Navbar button in Contact Page.
3. Preloader image is not responsive.

**Comment by swapnilsparsh** [comment]
SS

**Comment by tanishq-arya** [comment]
> > > git pull --tags -r
> > > Your configuration specifies to merge with the ref 'refs/heads/font-sizes'
> > > from the remote, but no such ref was fetched.
> 
> 1. Align the More Details Button in Women's Rights.
> 2. Navbar button in Contact Page.
> 3. Preloader image is not responsive.

@swapnilsparsh 
1. Fixed the button
2. Navbar button is in the contact page PR
3. I tried for the preloader but I don't think I can make it work for smaller screens, it overlaps and everything gets disturbed, If you wish I can remove the preloader for smaller screens.

**Comment by swapnilsparsh** [comment]
@tanishq-arya Try to fix the preloader for the mobile screen if not then tell me I will merge the PR.

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
ss

You will fix this bug in this issue or in the contact page issue?

**Comment by tanishq-arya** [comment]
@swapnilsparsh I added 2 cols for medium I hope it's okay. Also I added a gap in between rows in mobile view.

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh I added 2 cols for medium I hope it's okay. Also I added a gap in between rows in mobile view.

Still, the bug is there.

**Comment by tanishq-arya** [comment]
image

**Comment by tanishq-arya** [comment]
It's okay on my side.

**Comment by tanishq-arya** [comment]
> > @swapnilsparsh I added 2 cols for medium I hope it's okay. Also I added a gap in between rows in mobile view.
> 
> Still, the bug is there.

Its working fine on my end. Can you check again.

**Pull request merged**
