### PR TITLE
added delete account feature

### PR DESCRIPTION
**Pull request by coding-geek21**
## Related Issue or bug
added delete account feature

Fixes: #242 

#### Describe the changes you've made

User will be able to delete the account after login using delete account option , this also deletes the contacts saved under the user

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |
 
 

https://user-images.githubusercontent.com/53329034/114509772-8dca5c00-9c53-11eb-960d-188c71cce01f.mp4

### CODE REVIEW

**Comment by coding-geek21** [comment]
@swapnilsparsh  Please review this PR, Thank you!

**Comment by swapnilsparsh** [comment]
@coding-geek21 Great work but I want you to add this feature to profile section which is in development rather than adding it to navbar.
@sakshikhachane What's your POV ?

**Comment by sakshikhachane** [comment]
@coding-geek21 I also feel the same. But I think we can ask the assignee of issue #194 to integrate this feature in the profile section as she hasn't created the PR for now.

**Comment by SnehaVeerakumar** [comment]
This looks cool. I will surely consider this. By today I will make a PR and I can look into this feature too ! @sakshikhachane @swapnilsparsh 
Most probably I will add this feature too while making a PR for #194  issue.

**Comment by coding-geek21** [comment]
> @coding-geek21 Great work but I want you to add this feature to profile section which is in development rather than adding it to navbar.
> @sakshikhachane What's your POV ?

@swapnilsparsh  I will wait for #194 too get merged and add this feature there or get this merged so that person working on #194 issue can integrate it  while making PR

**Comment by SnehaVeerakumar** [comment]
I guess after merging my PR, you can create separate issue and make a PR. I guess that would be fine @swapnilsparsh

**Pull request merged**
